from __future__ import annotations

# The service lease and Compose health windows mirror this explicit cold-start budget.
PROVISION_TIMEOUT_SECONDS = 360.0
RUNTIME_VALIDATION_TIMEOUT_SECONDS = 60.0
WORKER_START_TIMEOUT_SECONDS = 30.0
SERVICE_STARTUP_TIMEOUT_SECONDS = (
    PROVISION_TIMEOUT_SECONDS
    + RUNTIME_VALIDATION_TIMEOUT_SECONDS
    + WORKER_START_TIMEOUT_SECONDS
)
