// Generated by packages/shared/scripts/sync-public-contract.ts. Do not edit by hand.
export {
  type PluginData,
  PluginDataSchema,
  type PluginManifest,
  PluginManifestSchema,
  type TranslationAdvise,
  TranslationAdviseSchema,
  type TranslationSuggestion,
  TranslationSuggestionSchema,
} from "../../index.ts";
