ALTER TYPE "PluginServiceType" ADD VALUE 'TERM_RECOGNIZER' BEFORE 'TRANSLATABLE_FILE_HANDLER';--> statement-breakpoint
ALTER TYPE "PluginServiceType" ADD VALUE 'TERM_ALIGNER' BEFORE 'TRANSLATABLE_FILE_HANDLER';--> statement-breakpoint
ALTER TYPE "PluginServiceType" ADD VALUE 'QA_CHECKER';