version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    versioning-strategy: increase
    open-pull-requests-limit: 20
    groups:
      aws-sdk:
        applies-to: version-updates
        patterns:
          - "@aws-sdk/*"
        update-types:
          - patch
          - minor
      orpc:
        applies-to: version-updates
        patterns:
          - "@orpc/*"
        update-types:
          - patch
          - minor
      playwright:
        applies-to: version-updates
        patterns:
          - playwright
          - "@playwright/*"
        update-types:
          - patch
          - minor
      vitest:
        applies-to: version-updates
        patterns:
          - vitest
          - "@vitest/*"
        update-types:
          - patch
          - minor
      vue-core:
        applies-to: version-updates
        patterns:
          - vue
          - "@vue/compiler-*"
        update-types:
          - patch
          - minor
      vueuse:
        applies-to: version-updates
        patterns:
          - "@vueuse/*"
        update-types:
          - patch
          - minor
      drizzle-core:
        applies-to: version-updates
        patterns:
          - drizzle-kit
          - drizzle-orm
        update-types:
          - patch
          - minor
    ignore:
      - dependency-name: "@types/node"
        update-types:
          - version-update:semver-major

  - package-ecosystem: docker
    directory: /.devcontainer
    schedule:
      interval: weekly
    ignore:
      - dependency-name: node

  - package-ecosystem: docker
    directory: /apps/spacy-server
    schedule:
      interval: weekly

  - package-ecosystem: uv
    directory: /apps/spacy-server
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
