services:
  redis:
    image: redis
    ports:
      - "127.0.0.1:6379:6379"
    user: "redis:redis"
  postgres:
    image: pgvector/pgvector:pg17
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: cat
    user: "postgres:postgres"
  infinity:
    image: michaelf34/infinity:0.0.75-trt-onnx
    volumes:
      - ./models/cache:/app/.cache
    ports:
      - 7997:7997
    command: v2 --revision "main" --dtype float16 --engine torch --port 7997
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
