packages:
  - apps/*
  - packages/*
  - "@cat-plugin/*"
  - tools/*

allowBuilds:
  "@swc/core": true
  better-sqlite3: true
  esbuild: true
  protobufjs: true
  vue-demi: true

peerDependencyRules:
  allowedVersions:
    tailwindcss: "4"
    zod: "4"

catalog:
  "@types/mdast": "^4.0.4"
  "@types/node": ^25.9.1
  "@vue/compiler-dom": ^3.5.35
  "@vue/compiler-sfc": ^3.5.35
  drizzle-kit: 1.0.0-rc.4-273829f
  drizzle-orm: 1.0.0-rc.4-273829f
  drizzle-seed: ^0.3.1
  remark-frontmatter: ^5.0.0
  remark-gfm: ^4.0.1
  remark-parse: ^11.0.0
  remark-stringify: ^11.0.0
  tsx: ^4.22.4
  unified: ^11.0.5
  unplugin-dts: 1.0.2
  vite: ^8.0.16
  vitest: ^4.1.8
  vue: ^3.5.35
  yaml: ^2.9.0
  zod: ^4.4.3
  vue-tsc: ^3.3.3

linkWorkspacePackages: true

syncInjectedDepsAfterScripts: ["build"]
