packages:
  - apps/*
  - packages/*
  - "@cat-plugin/*"
  - tools/*

allowBuilds:
  "@swc/core": true
  esbuild: true
  nx: true
  protobufjs: set this to true or false
  vue-demi: true

linkWorkspacePackages: true

syncInjectedDepsAfterScripts: [ "build" ]
