packages:
  - apps/*
  - e2e
  - packages/*
  - packages/@cat-plugin/*
  - "!**/dist/**"

onlyBuiltDependencies:
  - "@prisma/client"
  - "@prisma/engines"
  - esbuild
  - prisma
  - protobufjs

injectWorkspacePackages: true
