packages:
  - apps/*
  - packages/*
  - packages/@cat-plugin/*

ignoredBuiltDependencies:
  - esbuild
  - msgpackr-extract
  - oxc-resolver
  - protobufjs

linkWorkspacePackages: true

syncInjectedDepsAfterScripts: ["build"]

onlyBuiltDependencies:
  - "@swc/core"
  - "@tailwindcss/oxide"
  - nx
