packages:
  - apps/*
  - packages/*
  - packages/@cat-plugin/*

ignoredBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - esbuild
  - msgpackr-extract
  - oxc-resolver
  - prisma
  - protobufjs

injectWorkspacePackages: true

onlyBuiltDependencies:
  - '@swc/core'
  - '@tailwindcss/oxide'
  - nx
