packages:
  - apps/*
  - packages/*
  - "@cat-plugin/*"
  - tools/*

allowBuilds:
  "@swc/core": true
  better-sqlite3: true
  esbuild: true
  protobufjs: true
  vue-demi: true

catalog:
  "@vue/compiler-dom": ^3.5.32
  "@vue/compiler-sfc": ^3.5.32
  "@types/node": ^24.12.2
  tsx: ^4.21.0
  unplugin-dts: 1.0.0-beta.6
  vite: ^8.0.8
  vitest: ^4.1.4
  vue: ^3.5.32
  zod: ^4.3.6
  yaml: ^2.8.3
  unified: ^11.0.5
  remark-parse: ^11.0.0
  remark-stringify: ^11.0.0
  remark-gfm: ^4.0.1
  remark-frontmatter: ^5.0.0
  "@types/mdast": "^4.0.4"

linkWorkspacePackages: true

syncInjectedDepsAfterScripts: ["build"]
