packages:
  - apps/*
  - e2e
  - packages/*
  - packages/@cat-plugin/*

injectWorkspacePackages: true
nodeLinker: "pnp"
symlink: false

onlyBuiltDependencies:
  - "@prisma/client"
  - "@prisma/engines"
  - esbuild
  - prisma
  - protobufjs
  - "@swc/core"
  - msgpackr-extract
  - nx
  - oxc-resolver
