packages:
  - apps/*
  - packages/*
  - packages/@cat-plugin/*

ignoredBuiltDependencies:
  - "@prisma/client"
  - "@prisma/engines"
  - esbuild
  - msgpackr-extract
  - oxc-resolver
  - prisma
  - protobufjs

onlyBuiltDependencies:
  - "@swc/core"
  - nx

overrides:
  vite: "npm:rolldown-vite@latest"
