// Generated by packages/db/src/zod/codegen.ts. Do not edit by hand.
import * as z from "zod/v4";

import { AgentDefinitionSchema as AgentDefJsonSchema } from "../agent.ts";
import { nonNullSafeZDotJson, safeZDotJson } from "../json.ts";
import { DrizzleDateTimeSchema } from "../misc.ts";

export const AgentDefinitionSchema = z.object({
  id: z.int(),
  externalId: z.uuidv4(),
  scopeType: z.enum(["GLOBAL", "PROJECT", "USER"]),
  scopeId: z.string(),
  name: z.string(),
  description: z.string(),
  type: z.enum(["GENERAL", "GHOST_TEXT"]),
  definition: AgentDefJsonSchema,
  isBuiltin: z.boolean(),
  createdAt: DrizzleDateTimeSchema,
  updatedAt: DrizzleDateTimeSchema,
});

export type AgentDefinition = z.infer<typeof AgentDefinitionSchema>;

export const AgentSessionSchema = z.object({
  id: z.int(),
  externalId: z.uuidv4(),
  agentDefinitionId: z.int(),
  userId: z.uuidv4().nullable(),
  status: z.enum(["ACTIVE", "COMPLETED", "FAILED", "CANCELLED"]),
  currentRunId: z.int().nullable(),
  trustPolicy: z.enum(["CONFIRM_ALL", "TRUST_SESSION"]),
  metadata: nonNullSafeZDotJson,
  createdAt: DrizzleDateTimeSchema,
  updatedAt: DrizzleDateTimeSchema,
});

export type AgentSession = z.infer<typeof AgentSessionSchema>;

export const AgentRunSchema = z.object({
  id: z.int(),
  externalId: z.uuidv4(),
  sessionId: z.int(),
  status: z.string(),
  graphDefinition: nonNullSafeZDotJson,
  blackboardSnapshot: safeZDotJson.nullable(),
  currentNodeId: z.string().nullable(),
  deduplicationKey: z.string().nullable(),
  startedAt: DrizzleDateTimeSchema,
  completedAt: DrizzleDateTimeSchema.nullable(),
  metadata: safeZDotJson.nullable(),
});

export type AgentRun = z.infer<typeof AgentRunSchema>;

export const AgentEventSchema = z.object({
  id: z.int(),
  runId: z.int(),
  eventId: z.uuidv4(),
  parentEventId: z.uuidv4().nullable(),
  nodeId: z.string().nullable(),
  type: z.string(),
  payload: nonNullSafeZDotJson,
  timestamp: DrizzleDateTimeSchema,
});

export type AgentEvent = z.infer<typeof AgentEventSchema>;

export const AgentExternalOutputSchema = z.object({
  id: z.int(),
  runId: z.int(),
  nodeId: z.string(),
  outputType: z.string(),
  outputKey: z.string(),
  payload: nonNullSafeZDotJson,
  idempotencyKey: z.string().nullable(),
  createdAt: DrizzleDateTimeSchema,
});

export type AgentExternalOutput = z.infer<typeof AgentExternalOutputSchema>;
