// Generated by packages/db/src/zod/codegen.ts. Do not edit by hand.
import * as z from "zod";
import { DrizzleDateTimeSchema } from "../misc.ts";
import { safeZDotJson } from "../json.ts";

export const ChangesetSchema = z.object({
  id: z.int(),
  externalId: z.uuidv4(),
  projectId: z.uuidv4(),
  agentRunId: z.int().nullable(),
  pullRequestId: z.int().nullable(),
  branchId: z.int().nullable(),
  status: z.enum(["PENDING", "APPROVED", "PARTIALLY_APPROVED", "REJECTED", "APPLIED", "CONFLICT"]),
  createdBy: z.uuidv4().nullable(),
  reviewedBy: z.uuidv4().nullable(),
  summary: z.string().nullable(),
  asyncStatus: z.enum(["ALL_READY", "HAS_PENDING", "HAS_FAILED"]).nullable(),
  reviewedAt: DrizzleDateTimeSchema.nullable(),
  appliedAt: DrizzleDateTimeSchema.nullable(),
  createdAt: DrizzleDateTimeSchema,
  updatedAt: DrizzleDateTimeSchema,
});

export type Changeset = z.infer<typeof ChangesetSchema>;

export const ChangesetEntrySchema = z.object({
  id: z.int(),
  changesetId: z.int(),
  entityType: z.enum(["translation", "auto_translation", "element", "document", "document_tree", "comment", "comment_reaction", "term", "term_concept", "memory_item", "project_settings", "project_member", "project_attributes", "context", "project", "issue"]),
  entityId: z.string(),
  action: z.enum(["CREATE", "UPDATE", "DELETE"]),
  before: safeZDotJson.nullable(),
  after: safeZDotJson.nullable(),
  fieldPath: z.string().nullable(),
  riskLevel: z.enum(["LOW", "MEDIUM", "HIGH"]),
  reviewStatus: z.enum(["PENDING", "APPROVED", "REJECTED", "CONFLICT"]),
  asyncStatus: z.enum(["READY", "PENDING", "FAILED"]).nullable(),
  asyncTaskIds: z.array(z.string()).nullable(),
  createdAt: DrizzleDateTimeSchema,
  updatedAt: DrizzleDateTimeSchema,
});

export type ChangesetEntry = z.infer<typeof ChangesetEntrySchema>;

export const EntitySnapshotSchema = z.object({
  id: z.int(),
  externalId: z.uuidv4(),
  projectId: z.uuidv4(),
  name: z.string(),
  description: z.string().nullable(),
  level: z.string(),
  scopeFilter: safeZDotJson.nullable(),
  createdBy: z.uuidv4().nullable(),
  createdAt: DrizzleDateTimeSchema,
  updatedAt: DrizzleDateTimeSchema,
});

export type EntitySnapshot = z.infer<typeof EntitySnapshotSchema>;
