// Generated by packages/db/src/zod/codegen.ts. Do not edit by hand.
import * as z from "zod";
import { DrizzleDateTimeSchema } from "../misc.ts";

export const CommentSchema = z.object({
  id: z.int(),
  targetType: z.enum(["TRANSLATION", "ELEMENT"]),
  targetId: z.int(),
  userId: z.uuidv4(),
  content: z.string(),
  parentCommentId: z.int().nullable(),
  rootCommentId: z.int().nullable(),
  languageId: z.string(),
  createdAt: DrizzleDateTimeSchema,
  updatedAt: DrizzleDateTimeSchema,
});

export type Comment = z.infer<typeof CommentSchema>;

export const CommentReactionSchema = z.object({
  id: z.int(),
  commentId: z.int(),
  userId: z.uuidv4(),
  type: z.enum(["+1", "-1", "LAUGH", "HOORAY", "CONFUSED", "HEART", "ROCKET", "EYES"]),
  createdAt: DrizzleDateTimeSchema,
  updatedAt: DrizzleDateTimeSchema,
});

export type CommentReaction = z.infer<typeof CommentReactionSchema>;
