// Generated by packages/db/src/zod/codegen.ts. Do not edit by hand.
import * as z from "zod";
import { ContentRelationAllowedEndpointPairSchema, ContextProfilePayloadSchema, SemanticDiffEntryPayloadSchema } from "../content.ts";
import { DrizzleDateTimeSchema } from "../misc.ts";
import { safeZDotJson } from "../json.ts";

export const ContentNodeSchema = z.object({
  id: z.uuidv4(),
  projectId: z.uuidv4(),
  creatorId: z.uuidv4().nullable(),
  kind: z.enum(["PROJECT_ROOT", "DIRECTORY", "FILE", "MARKDOWN_SECTION", "SOURCE_COMPONENT", "UI_ROUTE", "MODULE", "MOD", "VERSION", "NAMESPACE", "CHAPTER", "PACKAGE", "SCREENSHOT_TARGET", "CUSTOM"]),
  displayLabel: z.string(),
  importerId: z.string().nullable(),
  sourceRootRef: z.string().nullable(),
  stableSourceNodeRef: z.string().nullable(),
  sourceUri: z.string().nullable(),
  sourcePath: z.string().nullable(),
  sourceType: z.string().nullable(),
  languageId: z.string().nullable(),
  exportRole: z.enum(["NONE", "PROJECT_ROOT", "DIRECTORY", "FILE", "SECTION"]),
  boundaryType: z.enum(["PROJECT", "SOURCE_ROOT", "DIRECTORY", "FILE", "MODULE", "MOD", "NAMESPACE", "NONE"]),
  fileHandlerId: z.int().nullable(),
  fileId: z.int().nullable(),
  lifecycleStatus: z.enum(["ACTIVE", "DRAFT", "DELETED", "QUARANTINED"]),
  provenance: safeZDotJson.nullable(),
  metadata: safeZDotJson.nullable(),
  createdAt: DrizzleDateTimeSchema,
  updatedAt: DrizzleDateTimeSchema,
});

export type ContentNode = z.infer<typeof ContentNodeSchema>;

export const ContentRelationTypeSchema = z.object({
  id: z.int(),
  namespace: z.string(),
  name: z.string(),
  version: z.string(),
  ownerPluginId: z.string().nullable(),
  semanticFamily: z.enum(["CONTAINMENT", "ORDERING", "SOURCE_REFERENCE", "SCOPE", "DEPENDENCY", "VERSIONING", "EVIDENCE", "DISCUSSION", "DUPLICATE", "SEMANTIC", "CUSTOM"]),
  allowedEndpointPairs: z.array(ContentRelationAllowedEndpointPairSchema),
  directionality: z.enum(["DIRECTED", "UNDIRECTED"]),
  participatesInContainment: z.boolean(),
  participatesInExport: z.boolean(),
  supportsOrdering: z.boolean(),
  weightingEligible: z.boolean(),
  defaultTrustLevel: z.enum(["UNTRUSTED", "COLLECTED", "VERIFIED", "REVIEW_APPROVED"]),
  deprecation: safeZDotJson.nullable(),
  migration: safeZDotJson.nullable(),
  metadata: safeZDotJson.nullable(),
  createdAt: DrizzleDateTimeSchema,
  updatedAt: DrizzleDateTimeSchema,
});

export type ContentRelationType = z.infer<typeof ContentRelationTypeSchema>;

export const ContentRelationSchema = z.object({
  id: z.uuidv4(),
  projectId: z.uuidv4(),
  relationTypeId: z.int(),
  sourceEndpointKind: z.enum(["NODE", "ELEMENT"]),
  sourceNodeId: z.uuidv4().nullable(),
  sourceElementId: z.int().nullable(),
  targetEndpointKind: z.enum(["NODE", "ELEMENT"]),
  targetNodeId: z.uuidv4().nullable(),
  targetElementId: z.int().nullable(),
  isPrimary: z.boolean(),
  localOrder: z.int().nullable(),
  confidenceBasisPoints: z.int(),
  lifecycleStatus: z.enum(["ACTIVE", "DRAFT", "DEPRECATED", "DELETED"]),
  weightHint: safeZDotJson.nullable(),
  provenance: safeZDotJson.nullable(),
  validationMetadata: safeZDotJson.nullable(),
  createdAt: DrizzleDateTimeSchema,
  updatedAt: DrizzleDateTimeSchema,
});

export type ContentRelation = z.infer<typeof ContentRelationSchema>;

export const ContentNodeToTaskSchema = z.object({
  contentNodeId: z.uuidv4(),
  taskId: z.uuidv4(),
});

export type ContentNodeToTask = z.infer<typeof ContentNodeToTaskSchema>;

export const TranslatableElementSchema = z.object({
  id: z.int(),
  projectId: z.uuidv4(),
  importerId: z.string(),
  sourceRootRef: z.string(),
  sourceNodeRef: z.string(),
  stableSourceRef: z.string(),
  identityStatus: z.enum(["ACTIVE", "DELETED", "QUARANTINED", "CONFLICT"]),
  identityConfidence: z.int(),
  meta: safeZDotJson.nullable(),
  sourceStartLine: z.int().nullable(),
  sourceEndLine: z.int().nullable(),
  sourceLocationMeta: safeZDotJson.nullable(),
  creatorId: z.uuidv4().nullable(),
  vectorizedStringId: z.int(),
  approvedTranslationId: z.int().nullable(),
  createdAt: DrizzleDateTimeSchema,
  updatedAt: DrizzleDateTimeSchema,
});

export type TranslatableElement = z.infer<typeof TranslatableElementSchema>;

export const VectorizedStringSchema = z.object({
  id: z.int(),
  value: z.string(),
  languageId: z.string(),
  chunkSetId: z.int().nullable(),
  status: z.string(),
});

export type VectorizedString = z.infer<typeof VectorizedStringSchema>;

export const ContextEvidenceSchema = z.object({
  id: z.int(),
  projectId: z.uuidv4(),
  attachedEndpointKind: z.string(),
  contentNodeId: z.uuidv4().nullable(),
  contentRelationId: z.uuidv4().nullable(),
  translatableElementId: z.int().nullable(),
  kind: z.enum(["TEXT", "JSON", "FILE", "MARKDOWN", "URL", "IMAGE", "SOURCE_LOCATION", "COMMENT", "SCREENSHOT", "GENERATED_ANALYSIS", "EXTERNAL_REFERENCE"]),
  trustLevel: z.enum(["UNTRUSTED", "COLLECTED", "VERIFIED", "REVIEW_APPROVED"]),
  freshnessAt: DrizzleDateTimeSchema.nullable(),
  jsonData: safeZDotJson.nullable(),
  fileId: z.int().nullable(),
  storageProviderId: z.int().nullable(),
  textData: z.string().nullable(),
  displayLabel: z.string().nullable(),
  provenance: safeZDotJson.nullable(),
  graphExplanation: safeZDotJson.nullable(),
  createdAt: DrizzleDateTimeSchema,
  updatedAt: DrizzleDateTimeSchema,
});

export type ContextEvidence = z.infer<typeof ContextEvidenceSchema>;

export const ContextProfileSchema = z.object({
  id: z.uuidv4(),
  projectId: z.uuidv4(),
  name: z.string(),
  payload: ContextProfilePayloadSchema,
  isDefault: z.boolean(),
  createdAt: DrizzleDateTimeSchema,
  updatedAt: DrizzleDateTimeSchema,
});

export type ContextProfile = z.infer<typeof ContextProfileSchema>;

export const ScopeBindingSchema = z.object({
  id: z.int(),
  projectId: z.uuidv4(),
  assetKind: z.enum(["GLOSSARY", "TERM_CONCEPT", "TERM", "MEMORY", "MEMORY_ITEM", "QA_PROFILE", "CONTEXT_PROFILE"]),
  assetId: z.string(),
  mode: z.enum(["ELIGIBLE_ONLY", "BOOST"]),
  contentNodeId: z.uuidv4().nullable(),
  contentRelationId: z.uuidv4().nullable(),
  weightBoost: z.int(),
  metadata: safeZDotJson.nullable(),
  createdAt: DrizzleDateTimeSchema,
  updatedAt: DrizzleDateTimeSchema,
});

export type ScopeBinding = z.infer<typeof ScopeBindingSchema>;

export const SemanticDiffEntrySchema = z.object({
  id: z.int(),
  projectId: z.uuidv4(),
  changesetId: z.int().nullable(),
  diffKind: z.enum(["CREATE", "DELETE", "SOURCE_TEXT_UPDATE", "MOVE", "REPARENT", "RELATION_ADD", "RELATION_REMOVE", "EVIDENCE_UPDATE", "METADATA_ONLY", "IDENTITY_CONFLICT"]),
  elementId: z.int().nullable(),
  contentNodeId: z.uuidv4().nullable(),
  contentRelationId: z.uuidv4().nullable(),
  vectorInvalidationReason: z.enum(["NEW_SOURCE_TEXT", "SOURCE_TEXT_CHANGED", "NOT_REQUIRED", "IDENTITY_CONFLICT"]),
  payload: SemanticDiffEntryPayloadSchema,
  createdAt: DrizzleDateTimeSchema,
  updatedAt: DrizzleDateTimeSchema,
});

export type SemanticDiffEntry = z.infer<typeof SemanticDiffEntrySchema>;
