// Generated by packages/db/src/zod/codegen.ts. Do not edit by hand.
import * as z from "zod/v4";
import { DrizzleDateTimeSchema } from "../misc.ts";
import { safeZDotJson } from "../json.ts";

export const DocumentSchema = z.object({
  id: z.uuidv4(),
  name: z.string().nullable(),
  projectId: z.uuidv4(),
  creatorId: z.uuidv4(),
  fileHandlerId: z.int().nullable(),
  fileId: z.int().nullable(),
  isDirectory: z.boolean(),
  createdAt: DrizzleDateTimeSchema,
  updatedAt: DrizzleDateTimeSchema,
});

export type Document = z.infer<typeof DocumentSchema>;

export const DocumentClosureSchema = z.object({
  ancestor: z.uuidv4(),
  descendant: z.uuidv4(),
  depth: z.int(),
  projectId: z.uuidv4(),
});

export type DocumentClosure = z.infer<typeof DocumentClosureSchema>;

export const DocumentToTaskSchema = z.object({
  documentId: z.uuidv4(),
  taskId: z.uuidv4(),
});

export type DocumentToTask = z.infer<typeof DocumentToTaskSchema>;

export const TranslatableElementSchema = z.object({
  id: z.int(),
  meta: safeZDotJson.nullable(),
  documentId: z.uuidv4(),
  sortIndex: z.int().nullable(),
  sourceStartLine: z.int().nullable(),
  sourceEndLine: z.int().nullable(),
  sourceLocationMeta: safeZDotJson.nullable(),
  creatorId: z.uuidv4().nullable(),
  vectorizedStringId: z.int(),
  approvedTranslationId: z.int().nullable(),
  createdAt: DrizzleDateTimeSchema,
  updatedAt: DrizzleDateTimeSchema,
});

export type TranslatableElement = z.infer<typeof TranslatableElementSchema>;

export const VectorizedStringSchema = z.object({
  id: z.int(),
  value: z.string(),
  languageId: z.string(),
  chunkSetId: z.int().nullable(),
  status: z.string(),
});

export type VectorizedString = z.infer<typeof VectorizedStringSchema>;

export const TranslatableElementContextSchema = z.object({
  id: z.int(),
  type: z.enum(["TEXT", "JSON", "FILE", "MARKDOWN", "URL"]),
  jsonData: safeZDotJson.nullable(),
  fileId: z.int().nullable(),
  storageProviderId: z.int().nullable(),
  textData: z.string().nullable(),
  translatableElementId: z.int(),
  createdAt: DrizzleDateTimeSchema,
  updatedAt: DrizzleDateTimeSchema,
});

export type TranslatableElementContext = z.infer<typeof TranslatableElementContextSchema>;
