// Generated by packages/db/src/zod/codegen.ts. Do not edit by hand.
import * as z from "zod/v4";
import { DrizzleDateTimeSchema } from "../misc.ts";

export const EntityBranchSchema = z.object({
  id: z.int(),
  externalId: z.uuidv4(),
  projectId: z.uuidv4(),
  name: z.string(),
  status: z.enum(["ACTIVE", "MERGED", "ABANDONED"]),
  hasConflicts: z.boolean(),
  baseChangesetId: z.int().nullable(),
  createdBy: z.uuidv4().nullable(),
  createdByAgentId: z.int().nullable(),
  mergedAt: DrizzleDateTimeSchema.nullable(),
  createdAt: DrizzleDateTimeSchema,
  updatedAt: DrizzleDateTimeSchema,
});

export type EntityBranch = z.infer<typeof EntityBranchSchema>;
