// Generated by packages/db/src/zod/codegen.ts. Do not edit by hand.
import * as z from "zod/v4";

import { DrizzleDateTimeSchema } from "../misc.ts";

export const FileSchema = z.object({
  id: z.int(),
  name: z.string(),
  createdAt: DrizzleDateTimeSchema,
  blobId: z.int(),
  isActive: z.boolean(),
});

export type File = z.infer<typeof FileSchema>;

export const BlobSchema = z.object({
  id: z.int(),
  key: z.string(),
  storageProviderId: z.int(),
  referenceCount: z.int(),
  hash: z.instanceof(Buffer).nullable(),
  createdAt: DrizzleDateTimeSchema,
});

export type Blob = z.infer<typeof BlobSchema>;
