// Generated by packages/db/src/zod/codegen.ts. Do not edit by hand.
import * as z from "zod/v4";
import { DrizzleDateTimeSchema } from "../misc.ts";
import { safeZDotJson } from "../json.ts";

export const GlossarySchema = z.object({
  id: z.uuidv4(),
  name: z.string(),
  description: z.string().nullable(),
  creatorId: z.uuidv4(),
  createdAt: DrizzleDateTimeSchema,
  updatedAt: DrizzleDateTimeSchema,
});

export type Glossary = z.infer<typeof GlossarySchema>;

export const GlossaryToProjectSchema = z.object({
  glossaryId: z.uuidv4(),
  projectId: z.uuidv4(),
});

export type GlossaryToProject = z.infer<typeof GlossaryToProjectSchema>;

export const TermSchema = z.object({
  id: z.int(),
  type: z.enum(["NOT_SPECIFIED", "FULL_FORM", "ACRONYM", "ABBREVIATION", "SHORT_FORM", "VARIANT", "PHRASE"]),
  status: z.enum(["NOT_SPECIFIED", "PREFERRED", "ADMITTED", "NOT_RECOMMENDED", "OBSOLETE"]),
  creatorId: z.uuidv4().nullable(),
  text: z.string(),
  languageId: z.string(),
  termConceptId: z.int(),
  createdAt: DrizzleDateTimeSchema,
  updatedAt: DrizzleDateTimeSchema,
});

export type Term = z.infer<typeof TermSchema>;

export const TermConceptSchema = z.object({
  id: z.int(),
  definition: z.string().nullable(),
  stringId: z.int().nullable(),
  creatorId: z.uuidv4().nullable(),
  glossaryId: z.uuidv4(),
  createdAt: DrizzleDateTimeSchema,
  updatedAt: DrizzleDateTimeSchema,
});

export type TermConcept = z.infer<typeof TermConceptSchema>;

export const TermConceptToSubjectSchema = z.object({
  termConceptId: z.int(),
  subjectId: z.int(),
  isPrimary: z.boolean(),
});

export type TermConceptToSubject = z.infer<typeof TermConceptToSubjectSchema>;

export const TermConceptSubjectSchema = z.object({
  id: z.int(),
  subject: z.string(),
  defaultDefinition: z.string().nullable(),
  creatorId: z.uuidv4().nullable(),
  glossaryId: z.uuidv4().nullable(),
  createdAt: DrizzleDateTimeSchema,
  updatedAt: DrizzleDateTimeSchema,
});

export type TermConceptSubject = z.infer<typeof TermConceptSubjectSchema>;

export const TermRecallVariantSchema = z.object({
  id: z.int(),
  conceptId: z.int(),
  languageId: z.string(),
  text: z.string(),
  normalizedText: z.string(),
  variantType: z.enum(["SURFACE", "CASE_FOLDED", "LEMMA", "TOKEN_TEMPLATE", "FRAGMENT"]),
  meta: safeZDotJson.nullable(),
  createdAt: DrizzleDateTimeSchema,
  updatedAt: DrizzleDateTimeSchema,
});

export type TermRecallVariant = z.infer<typeof TermRecallVariantSchema>;
