// Generated by packages/db/src/zod/codegen.ts. Do not edit by hand.
import * as z from "zod";
import { DrizzleDateTimeSchema } from "../misc.ts";
import { safeZDotJson } from "../json.ts";

export const IssueCommentThreadSchema = z.object({
  id: z.int(),
  externalId: z.uuidv4(),
  targetType: z.enum(["issue", "pr"]),
  targetId: z.int(),
  isReviewThread: z.boolean(),
  isResolved: z.boolean(),
  reviewContext: safeZDotJson.nullable(),
  createdAt: DrizzleDateTimeSchema,
});

export type IssueCommentThread = z.infer<typeof IssueCommentThreadSchema>;

export const IssueCommentSchema = z.object({
  id: z.int(),
  externalId: z.uuidv4(),
  threadId: z.int(),
  body: z.string(),
  authorId: z.uuidv4().nullable(),
  authorAgentId: z.int().nullable(),
  editedAt: DrizzleDateTimeSchema.nullable(),
  createdAt: DrizzleDateTimeSchema,
});

export type IssueComment = z.infer<typeof IssueCommentSchema>;

export const CrossReferenceSchema = z.object({
  id: z.int(),
  sourceType: z.enum(["issue", "pr", "issue_comment"]),
  sourceId: z.int(),
  targetType: z.enum(["issue", "pr"]),
  targetId: z.int(),
  projectId: z.uuidv4(),
  createdAt: DrizzleDateTimeSchema,
});

export type CrossReference = z.infer<typeof CrossReferenceSchema>;
