// Generated by packages/db/src/zod/codegen.ts. Do not edit by hand.
import * as z from "zod/v4";
import { DrizzleDateTimeSchema } from "../misc.ts";
import { nonNullSafeZDotJson, safeZDotJson } from "../json.ts";

export const ProjectSequenceSchema = z.object({
  id: z.int(),
  projectId: z.uuidv4(),
  nextValue: z.int(),
});

export type ProjectSequence = z.infer<typeof ProjectSequenceSchema>;

export const IssueSchema = z.object({
  id: z.int(),
  externalId: z.uuidv4(),
  projectId: z.uuidv4(),
  number: z.int(),
  title: z.string(),
  body: z.string(),
  status: z.enum(["OPEN", "CLOSED"]),
  authorId: z.uuidv4().nullable(),
  authorAgentId: z.int().nullable(),
  assignees: nonNullSafeZDotJson,
  claimPolicy: safeZDotJson.nullable(),
  parentIssueId: z.int().nullable(),
  closedAt: DrizzleDateTimeSchema.nullable(),
  closedByPRId: z.int().nullable(),
  metadata: safeZDotJson.nullable(),
  createdAt: DrizzleDateTimeSchema,
  updatedAt: DrizzleDateTimeSchema,
});

export type Issue = z.infer<typeof IssueSchema>;

export const IssueLabelSchema = z.object({
  issueId: z.int(),
  label: z.string(),
});

export type IssueLabel = z.infer<typeof IssueLabelSchema>;
