// Generated by packages/db/src/zod/codegen.ts. Do not edit by hand.
import * as z from "zod/v4";
import { KanbanCardStatusValues } from "../enum.ts";
import { DrizzleDateTimeSchema } from "../misc.ts";
import { safeZDotJson, nonNullSafeZDotJson } from "../json.ts";

export const KanbanBoardSchema = z.object({
  id: z.int(),
  externalId: z.uuidv4(),
  orgId: z.uuidv4().nullable(),
  name: z.string(),
  /** Ordered column metadata list */
  columns: nonNullSafeZDotJson,
  linkedResourceType: z.string().nullable(),
  linkedResourceId: z.string().nullable(),
  metadata: safeZDotJson.nullable(),
  createdAt: DrizzleDateTimeSchema,
  updatedAt: DrizzleDateTimeSchema,
});

export type KanbanBoard = z.infer<typeof KanbanBoardSchema>;

export const KanbanCardSchema = z.object({
  id: z.int(),
  externalId: z.uuidv4(),
  boardId: z.int(),
  columnId: z.string(),
  title: z.string(),
  description: z.string(),
  assigneeAgentId: z.int().nullable(),
  assigneeUserId: z.uuidv4().nullable(),
  claimedAt: DrizzleDateTimeSchema.nullable(),
  claimedBy: z.string().nullable(),
  priority: z.int(),
  dueDate: DrizzleDateTimeSchema.nullable(),
  labels: z.array(z.string()),
  linkedResourceType: z.string().nullable(),
  linkedResourceId: z.string().nullable(),
  status: z.enum(KanbanCardStatusValues),
  parentCardId: z.int().nullable(),
  batchSize: z.int(),
  metadata: safeZDotJson.nullable(),
  createdAt: DrizzleDateTimeSchema,
  updatedAt: DrizzleDateTimeSchema,
});

export type KanbanCard = z.infer<typeof KanbanCardSchema>;

export const ToolCallLogSchema = z.object({
  id: z.int(),
  sessionId: z.int(),
  runId: z.int(),
  nodeId: z.string().nullable(),
  toolName: z.string(),
  arguments: nonNullSafeZDotJson,
  result: safeZDotJson.nullable(),
  error: z.string().nullable(),
  durationMs: z.int().nullable(),
  sideEffectType: z.string(),
  createdAt: DrizzleDateTimeSchema,
});

export type ToolCallLog = z.infer<typeof ToolCallLogSchema>;
