// Generated by packages/db/src/zod/codegen.ts. Do not edit by hand.
import * as z from "zod";
import { DrizzleDateTimeSchema } from "#/schema/misc.ts";
import { LanguageAnalysisRequirementAssessmentSchema } from "#/schema/language-analysis-requirement.ts";
import { LanguageAnalysisSelectionFingerprintSchema } from "#/schema/language-analysis-requirement.ts";
import { ServiceImplementationReferenceSchema } from "#/schema/service-implementation-reference.ts";

export const LanguageAnalysisSelectionRecordSchema = z.object({
  key: z.string(),
  implementation: ServiceImplementationReferenceSchema.nullable(),
  revision: z.int(),
  configurationFingerprint: LanguageAnalysisSelectionFingerprintSchema.nullable(),
  createdAt: DrizzleDateTimeSchema,
  updatedAt: DrizzleDateTimeSchema,
});

export type LanguageAnalysisSelectionRecord = z.infer<typeof LanguageAnalysisSelectionRecordSchema>;

export const LanguageAnalysisObservationRecordSchema = z.object({
  languageId: z.string(),
  policyEpoch: z.int(),
  selectionKey: z.string(),
  selectionRevision: z.int(),
  configurationFingerprint: z.string(),
  assessment: LanguageAnalysisRequirementAssessmentSchema,
  observedAt: DrizzleDateTimeSchema,
  createdAt: DrizzleDateTimeSchema,
  updatedAt: DrizzleDateTimeSchema,
});

export type LanguageAnalysisObservationRecord = z.infer<typeof LanguageAnalysisObservationRecordSchema>;
