// Generated by packages/db/src/zod/codegen.ts. Do not edit by hand.
import * as z from "zod";
import { CanonicalInputVersionSchema, RecallDerivationBlockerSchema, RecallDerivationTargetIdSchema, RecallDerivationVersionSchema } from "#/schema/recall-derivation.ts";
import { DrizzleDateTimeSchema } from "#/schema/misc.ts";
import { MemoryRecallVariantMetaSchema } from "#/schema/memory-recall-derivation.ts";
import { NormalizedLanguageIdSchema } from "#/schema/language-analysis.ts";
import { TokenTypeSchema } from "#/schema/enum.ts";

export const SlotMappingEntrySchema = z.object({
  placeholder: z.string(),
  value: z.string(),
  tokenType: TokenTypeSchema,
});

export type SlotMappingEntry = z.infer<typeof SlotMappingEntrySchema>;

export const MemorySchema = z.object({
  id: z.uuidv4(),
  name: z.string(),
  description: z.string().nullable(),
  scope: z.enum(["PROJECT", "PERSONAL"]),
  creatorId: z.uuidv4(),
  createdAt: DrizzleDateTimeSchema,
  updatedAt: DrizzleDateTimeSchema,
});

export type Memory = z.infer<typeof MemorySchema>;

export const MemoryItemSchema = z.object({
  id: z.int(),
  creatorId: z.uuidv4().nullable(),
  memoryId: z.uuidv4(),
  sourceElementId: z.int().nullable(),
  translationId: z.int().nullable(),
  sourceStringId: z.int(),
  translationStringId: z.int(),
  createdAt: DrizzleDateTimeSchema,
  updatedAt: DrizzleDateTimeSchema,
});

export type MemoryItem = z.infer<typeof MemoryItemSchema>;

export const MemoryToProjectSchema = z.object({
  memoryId: z.uuidv4(),
  projectId: z.uuidv4(),
});

export type MemoryToProject = z.infer<typeof MemoryToProjectSchema>;

export const PersonalMemoryBindingSchema = z.object({
  memoryId: z.uuidv4(),
  projectId: z.uuidv4(),
  userId: z.uuidv4(),
  createdAt: DrizzleDateTimeSchema,
  updatedAt: DrizzleDateTimeSchema,
});

export type PersonalMemoryBinding = z.infer<typeof PersonalMemoryBindingSchema>;

export const MemoryPromotionRecordSchema = z.object({
  id: z.int(),
  projectId: z.uuidv4(),
  sourceTranslationId: z.int(),
  sourcePersonalMemoryItemId: z.int().nullable(),
  targetMemoryId: z.uuidv4().nullable(),
  targetMemoryItemId: z.int().nullable(),
  approvedById: z.uuidv4().nullable(),
  status: z.enum(["PENDING", "PROMOTED", "NO_PROJECT_MEMORY_TARGET"]),
  idempotencyKey: z.string(),
  createdAt: DrizzleDateTimeSchema,
  updatedAt: DrizzleDateTimeSchema,
});

export type MemoryPromotionRecord = z.infer<typeof MemoryPromotionRecordSchema>;

export const MemoryItemDeletionSchema = z.object({
  id: z.int(),
  deletedMemoryItemId: z.int(),
  memoryId: z.uuidv4().nullable(),
  projectId: z.uuidv4().nullable(),
  deletedById: z.uuidv4().nullable(),
  scope: z.enum(["PROJECT", "PERSONAL"]),
  reason: z.string().nullable(),
  deletedAt: DrizzleDateTimeSchema,
});

export type MemoryItemDeletion = z.infer<typeof MemoryItemDeletionSchema>;

export const RecallDerivationStateSchema = z.object({
  id: z.int(),
  targetKind: z.enum(["MEMORY_ITEM", "TERM_CONCEPT"]),
  targetId: RecallDerivationTargetIdSchema,
  languageId: NormalizedLanguageIdSchema,
  status: z.enum(["PENDING", "RUNNING", "FRESH", "BLOCKED", "FAILED"]),
  demandRevision: z.int(),
  executionEpoch: z.int(),
  leaseOwnerId: z.uuidv4().nullable(),
  leaseToken: z.uuidv4().nullable(),
  leaseExpiresAt: DrizzleDateTimeSchema.nullable(),
  retryCount: z.int(),
  nextAttemptAt: DrizzleDateTimeSchema.nullable(),
  blocker: RecallDerivationBlockerSchema.nullable(),
  canonicalInputVersion: CanonicalInputVersionSchema,
  requiredDerivationVersion: RecallDerivationVersionSchema.nullable(),
  currentCanonicalInputVersion: CanonicalInputVersionSchema.nullable(),
  currentDerivationVersion: RecallDerivationVersionSchema.nullable(),
  lastAttemptAt: DrizzleDateTimeSchema.nullable(),
  publishedAt: DrizzleDateTimeSchema.nullable(),
  createdAt: DrizzleDateTimeSchema,
  updatedAt: DrizzleDateTimeSchema,
});

export type RecallDerivationState = z.infer<typeof RecallDerivationStateSchema>;

export const MemoryRecallVariantSchema = z.object({
  id: z.int(),
  derivationStateId: z.int(),
  memoryItemId: z.int(),
  memoryId: z.uuidv4(),
  languageId: NormalizedLanguageIdSchema,
  querySide: z.enum(["SOURCE", "TRANSLATION"]),
  text: z.string(),
  normalizedText: z.string(),
  variantType: z.enum(["SURFACE", "CASE_FOLDED", "LEMMA", "TOKEN_TEMPLATE", "FRAGMENT"]),
  meta: MemoryRecallVariantMetaSchema.nullable(),
  canonicalInputVersion: CanonicalInputVersionSchema,
  recallDerivationVersion: RecallDerivationVersionSchema,
  createdAt: DrizzleDateTimeSchema,
  updatedAt: DrizzleDateTimeSchema,
});

export type MemoryRecallVariant = z.infer<typeof MemoryRecallVariantSchema>;
