// Generated by packages/db/src/zod/codegen.ts. Do not edit by hand.
import * as z from "zod/v4";
import { DrizzleDateTimeSchema } from "../misc.ts";
import { TokenTypeSchema } from "./enum.ts";

export const SlotMappingEntrySchema = z.object({
  placeholder: z.string(),
  value: z.string(),
  tokenType: TokenTypeSchema,
});

export type SlotMappingEntry = z.infer<typeof SlotMappingEntrySchema>;

export const MemorySchema = z.object({
  id: z.uuidv4(),
  name: z.string(),
  description: z.string().nullable(),
  creatorId: z.uuidv4(),
  createdAt: DrizzleDateTimeSchema,
  updatedAt: DrizzleDateTimeSchema,
});

export type Memory = z.infer<typeof MemorySchema>;

export const MemoryItemSchema = z.object({
  id: z.int(),
  creatorId: z.uuidv4().nullable(),
  memoryId: z.uuidv4(),
  sourceElementId: z.int().nullable(),
  translationId: z.int().nullable(),
  sourceStringId: z.int(),
  translationStringId: z.int(),
  sourceTemplate: z.string().nullable(),
  translationTemplate: z.string().nullable(),
  slotMapping: z.array(SlotMappingEntrySchema).nullable(),
  createdAt: DrizzleDateTimeSchema,
  updatedAt: DrizzleDateTimeSchema,
});

export type MemoryItem = z.infer<typeof MemoryItemSchema>;

export const MemoryToProjectSchema = z.object({
  memoryId: z.uuidv4(),
  projectId: z.uuidv4(),
});

export type MemoryToProject = z.infer<typeof MemoryToProjectSchema>;
