// Generated by packages/db/src/zod/codegen.ts. Do not edit by hand.
import * as z from "zod";
import { DrizzleDateTimeSchema } from "../misc.ts";
import { nonNullSafeZDotJson, safeZDotJson } from "../json.ts";

export const LanguageSchema = z.object({
  id: z.string(),
});

export type Language = z.infer<typeof LanguageSchema>;

export const TaskSchema = z.object({
  id: z.uuidv4(),
  status: z.enum(["COMPLETED", "PENDING", "FAILED"]),
  type: z.string(),
  meta: safeZDotJson.nullable(),
  createdAt: DrizzleDateTimeSchema,
  updatedAt: DrizzleDateTimeSchema,
});

export type Task = z.infer<typeof TaskSchema>;

export const SettingSchema = z.object({
  id: z.int(),
  key: z.string(),
  value: nonNullSafeZDotJson,
  createdAt: DrizzleDateTimeSchema,
  updatedAt: DrizzleDateTimeSchema,
});

export type Setting = z.infer<typeof SettingSchema>;
