// Generated by packages/db/src/zod/codegen.ts. Do not edit by hand.
import * as z from "zod";
import { DrizzleDateTimeSchema } from "#/schema/misc.ts";
import { TaskAffectedResourceSchema, TaskKindSchema, TaskPayloadSchema, TaskRuntimeSchema } from "#/schema/localization-task.ts";
import { nonNullSafeZDotJson, safeZDotJson } from "#/schema/json.ts";

export const LanguageSchema = z.object({
  id: z.string(),
});

export type Language = z.infer<typeof LanguageSchema>;

export const TaskSchema = z.object({
  id: z.uuidv4(),
  kind: z.enum(["BATCH_AUTO_TRANSLATION", "RECALL_DERIVATION"]),
  payload: TaskPayloadSchema,
  status: z.enum(["PENDING", "RUNNING", "COMPLETED", "FAILED", "BLOCKED", "CANCEL_REQUESTED", "CANCELED"]),
  scopeType: z.enum(["PROJECT", "USER", "INSTANCE"]),
  scopeId: z.uuidv4().nullable(),
  actorType: z.enum(["USER", "SYSTEM"]),
  actorId: z.uuidv4().nullable(),
  resources: z.array(TaskAffectedResourceSchema),
  revision: z.int(),
  progressCurrent: z.int().nullable(),
  progressTotal: z.int().nullable(),
  runtime: TaskRuntimeSchema,
  currentFailureId: z.uuidv4().nullable(),
  retryOfTaskId: z.uuidv4().nullable(),
  startedAt: DrizzleDateTimeSchema.nullable(),
  finishedAt: DrizzleDateTimeSchema.nullable(),
  createdAt: DrizzleDateTimeSchema,
  updatedAt: DrizzleDateTimeSchema,
}).superRefine((value, ctx) => {
  const parsed = TaskKindSchema.safeParse({
    kind: value.kind,
    payload: value.payload,
  });
  if (!parsed.success) {
    ctx.addIssue({ code: "custom", message: "Task kind and payload must agree." });
  }
});

export type Task = z.infer<typeof TaskSchema>;

export const WorkflowTaskDispatchSchema = z.object({
  id: z.uuidv4(),
  taskId: z.uuidv4(),
  generation: z.int(),
  runId: z.uuidv4(),
  status: z.enum(["REQUESTED", "CLAIMED", "RUNNING", "CANCELLING", "SETTLED"]),
  ownerId: z.uuidv4().nullable(),
  ownerEpoch: z.int(),
  ownerLeaseExpiresAt: DrizzleDateTimeSchema.nullable(),
  attemptCount: z.int(),
  agentSessionId: z.int().nullable(),
  lastProjectedEventSequence: z.int(),
  settledAt: DrizzleDateTimeSchema.nullable(),
  createdAt: DrizzleDateTimeSchema,
  updatedAt: DrizzleDateTimeSchema,
});

export type WorkflowTaskDispatch = z.infer<typeof WorkflowTaskDispatchSchema>;

export const OperationFailureRecordSchema = z.object({
  id: z.uuidv4(),
  code: z.enum(["CAT_OPERATION_CANCELED", "CAT_OPERATION_DEPENDENCY_UNAVAILABLE", "CAT_OPERATION_EXECUTION_DENIED", "CAT_OPERATION_INVALID_INPUT", "CAT_OPERATION_MISSING_CAPABILITY", "CAT_OPERATION_RESOURCE_NOT_FOUND", "CAT_OPERATION_FAILED", "CAT_OPERATION_PERMISSION_DENIED", "CAT_OPERATION_RELATIONSHIP_DENIED", "CAT_OPERATION_REVIEW_CHANGE_BLOCKED"]),
  message: z.string(),
  severity: z.enum(["INFO", "WARNING", "ERROR"]),
  retryable: z.boolean(),
  blocker: z.enum(["branch_translation_write_failed", "branch_write_context_unavailable", "candidate_channel_capability_unavailable", "candidate_channel_execution_failed", "language_analysis_duplicate_implementation", "language_analysis_installation_scope_mismatch", "language_analysis_invalid_attestation", "language_analysis_invalid_configuration", "language_analysis_invalid_response", "language_analysis_missing_implementation", "language_analysis_missing_selection", "language_analysis_policy_changed", "language_analysis_service_type_mismatch", "language_analysis_timeout", "language_analysis_unavailable", "language_analysis_unsupported_language", "recall_derivation_blocked", "recall_derivation_failed", "recall_derivation_pending", "recall_derivation_stale", "reviewable_change_write_failed"]).nullable(),
  capability: z.enum(["CANDIDATE_RECALL", "LANGUAGE_ANALYSIS", "RECALL_DERIVATION", "VECTOR_STORAGE", "TEXT_VECTORIZER"]).nullable(),
  authorizationDecision: z.enum(["api_key_scope_denied", "rebac_denied", "write_mode_denied"]).nullable(),
  affectedResources: z.array(TaskAffectedResourceSchema),
  remediationHint: z.string().nullable(),
  redactionBoundary: z.enum(["PUBLIC", "INTERNAL"]),
  taskId: z.uuidv4().nullable(),
  traceId: z.string().nullable(),
  createdAt: DrizzleDateTimeSchema,
});

export type OperationFailureRecord = z.infer<typeof OperationFailureRecordSchema>;

export const SettingSchema = z.object({
  id: z.int(),
  key: z.string(),
  value: nonNullSafeZDotJson,
  createdAt: DrizzleDateTimeSchema,
  updatedAt: DrizzleDateTimeSchema,
});

export type Setting = z.infer<typeof SettingSchema>;

export const RuntimeCacheEntrySchema = z.object({
  namespace: z.string(),
  key: z.string(),
  value: safeZDotJson,
  expiresAt: DrizzleDateTimeSchema.nullable(),
  lastAccessedAt: DrizzleDateTimeSchema.nullable(),
  createdAt: DrizzleDateTimeSchema,
  updatedAt: DrizzleDateTimeSchema,
});

export type RuntimeCacheEntry = z.infer<typeof RuntimeCacheEntrySchema>;

export const RuntimeSessionEntrySchema = z.object({
  key: z.string(),
  fields: z.record(z.string(), z.string()),
  expiresAt: DrizzleDateTimeSchema,
  createdAt: DrizzleDateTimeSchema,
  updatedAt: DrizzleDateTimeSchema,
});

export type RuntimeSessionEntry = z.infer<typeof RuntimeSessionEntrySchema>;

export const RuntimeQueueTaskSchema = z.object({
  queueName: z.string(),
  taskId: z.string(),
  payload: nonNullSafeZDotJson,
  status: z.enum(["PENDING", "PROCESSING", "SUCCEEDED", "FAILED"]),
  retryCount: z.int(),
  enqueuedAt: DrizzleDateTimeSchema,
  leasedUntil: DrizzleDateTimeSchema.nullable(),
  lastError: z.string().nullable(),
  createdAt: DrizzleDateTimeSchema,
  updatedAt: DrizzleDateTimeSchema,
});

export type RuntimeQueueTask = z.infer<typeof RuntimeQueueTaskSchema>;
