// Generated by packages/db/src/zod/codegen.ts. Do not edit by hand.
import * as z from "zod/v4";
import { DrizzleDateTimeSchema } from "../misc.ts";
import { _JSONSchemaSchema, nonNullSafeZDotJson, safeZDotJson } from "../json.ts";

export const PluginSchema = z.object({
  id: z.string(),
  name: z.string(),
  overview: z.string().nullable(),
  isExternal: z.boolean(),
  entry: z.string(),
  iconUrl: z.url().nullable(),
  version: z.string(),
  createdAt: DrizzleDateTimeSchema,
  updatedAt: DrizzleDateTimeSchema,
});

export type Plugin = z.infer<typeof PluginSchema>;

export const PluginInstallationSchema = z.object({
  id: z.int(),
  scopeId: z.string(),
  pluginId: z.string(),
  scopeMeta: safeZDotJson.nullable(),
  scopeType: z.enum(["GLOBAL", "PROJECT", "USER"]),
  createdAt: DrizzleDateTimeSchema,
  updatedAt: DrizzleDateTimeSchema,
});

export type PluginInstallation = z.infer<typeof PluginInstallationSchema>;

export const PluginConfigSchema = z.object({
  id: z.int(),
  pluginId: z.string(),
  schema: _JSONSchemaSchema,
  createdAt: DrizzleDateTimeSchema,
  updatedAt: DrizzleDateTimeSchema,
});

export type PluginConfig = z.infer<typeof PluginConfigSchema>;

export const PluginConfigInstanceSchema = z.object({
  id: z.int(),
  value: nonNullSafeZDotJson,
  creatorId: z.uuidv4().nullable(),
  configId: z.int(),
  pluginInstallationId: z.int(),
  createdAt: DrizzleDateTimeSchema,
  updatedAt: DrizzleDateTimeSchema,
});

export type PluginConfigInstance = z.infer<typeof PluginConfigInstanceSchema>;

export const PluginServiceSchema = z.object({
  id: z.int(),
  serviceId: z.string(),
  pluginInstallationId: z.int(),
  serviceType: z.enum(["AUTH_FACTOR", "STORAGE_PROVIDER", "FILE_IMPORTER", "FILE_EXPORTER", "TRANSLATION_ADVISOR", "TEXT_VECTORIZER", "VECTOR_STORAGE", "QA_CHECKER", "TOKENIZER", "LLM_PROVIDER", "AGENT_TOOL_PROVIDER", "AGENT_CONTEXT_PROVIDER", "NLP_WORD_SEGMENTER"]),
  createdAt: DrizzleDateTimeSchema,
  updatedAt: DrizzleDateTimeSchema,
});

export type PluginService = z.infer<typeof PluginServiceSchema>;

export const PluginComponentSchema = z.object({
  id: z.int(),
  componentId: z.string(),
  slot: z.string(),
  url: z.string(),
  pluginInstallationId: z.int(),
  createdAt: DrizzleDateTimeSchema,
  updatedAt: DrizzleDateTimeSchema,
});

export type PluginComponent = z.infer<typeof PluginComponentSchema>;

export const PluginPermissionSchema = z.object({
  id: z.int(),
  permission: z.string(),
  description: z.string(),
  pluginId: z.string(),
  createdAt: DrizzleDateTimeSchema,
  updatedAt: DrizzleDateTimeSchema,
});

export type PluginPermission = z.infer<typeof PluginPermissionSchema>;

export const PluginVersionSchema = z.object({
  id: z.int(),
  version: z.string(),
  pluginId: z.string(),
});

export type PluginVersion = z.infer<typeof PluginVersionSchema>;
