// Generated by packages/db/src/zod/codegen.ts. Do not edit by hand.
import * as z from "zod/v4";

import { DrizzleDateTimeSchema } from "../misc.ts";

export const ProjectSchema = z.object({
  id: z.uuidv4(),
  name: z.string(),
  description: z.string().nullable(),
  creatorId: z.uuidv4(),
  createdAt: DrizzleDateTimeSchema,
  updatedAt: DrizzleDateTimeSchema,
});

export type Project = z.infer<typeof ProjectSchema>;

export const ProjectTargetLanguageSchema = z.object({
  languageId: z.string(),
  projectId: z.uuidv4(),
});

export type ProjectTargetLanguage = z.infer<typeof ProjectTargetLanguageSchema>;
