// Generated by packages/db/src/zod/codegen.ts. Do not edit by hand.
import * as z from "zod/v4";
import { DrizzleDateTimeSchema } from "../misc.ts";
import { nonNullSafeZDotJson, safeZDotJson } from "../json.ts";

export const PullRequestSchema = z.object({
  id: z.int(),
  externalId: z.uuidv4(),
  projectId: z.uuidv4(),
  number: z.int(),
  title: z.string(),
  body: z.string(),
  status: z.enum(["DRAFT", "OPEN", "REVIEW", "CHANGES_REQUESTED", "MERGED", "CLOSED"]),
  authorId: z.uuidv4().nullable(),
  authorAgentId: z.int().nullable(),
  branchId: z.int(),
  issueId: z.int().nullable(),
  reviewers: nonNullSafeZDotJson,
  mergedAt: DrizzleDateTimeSchema.nullable(),
  mergedBy: z.string().nullable(),
  metadata: safeZDotJson.nullable(),
  type: z.enum(["MANUAL", "AUTO_TRANSLATE"]),
  targetLanguageId: z.string().nullable(),
  createdAt: DrizzleDateTimeSchema,
  updatedAt: DrizzleDateTimeSchema,
});

export type PullRequest = z.infer<typeof PullRequestSchema>;
