// Generated by packages/db/src/zod/codegen.ts. Do not edit by hand.
import * as z from "zod/v4";

import { nonNullSafeZDotJson } from "../json.ts";
import { DrizzleDateTimeSchema } from "../misc.ts";

export const QaResultSchema = z.object({
  id: z.int(),
  translationId: z.int(),
  createdAt: DrizzleDateTimeSchema,
  updatedAt: DrizzleDateTimeSchema,
});

export type QaResult = z.infer<typeof QaResultSchema>;

export const QaResultItemSchema = z.object({
  id: z.int(),
  meta: nonNullSafeZDotJson,
  isPassed: z.boolean(),
  resultId: z.int(),
  checkerId: z.int(),
  createdAt: DrizzleDateTimeSchema,
  updatedAt: DrizzleDateTimeSchema,
});

export type QaResultItem = z.infer<typeof QaResultItemSchema>;
