// Generated by packages/db/src/zod/codegen.ts. Do not edit by hand.
import * as z from "zod";
import { DrizzleDateTimeSchema } from "../misc.ts";
import { QaReviewProfileConfigSchema, QaReviewRunMetaSchema, QaReviewSpanSchema, QaReviewTextRangeSchema } from "../qa-review.ts";
import { nonNullSafeZDotJson, safeZDotJson } from "../json.ts";

export const QaResultSchema = z.object({
  id: z.int(),
  translationId: z.int(),
  createdAt: DrizzleDateTimeSchema,
  updatedAt: DrizzleDateTimeSchema,
});

export type QaResult = z.infer<typeof QaResultSchema>;

export const QaResultItemSchema = z.object({
  id: z.int(),
  meta: nonNullSafeZDotJson,
  isPassed: z.boolean(),
  resultId: z.int(),
  checkerId: z.int(),
  createdAt: DrizzleDateTimeSchema,
  updatedAt: DrizzleDateTimeSchema,
});

export type QaResultItem = z.infer<typeof QaResultItemSchema>;

export const QaReviewProfileSchema = z.object({
  id: z.int(),
  projectId: z.uuidv4(),
  languageId: z.string().nullable(),
  contentNodeId: z.uuidv4().nullable(),
  branchId: z.int().nullable(),
  name: z.string(),
  config: QaReviewProfileConfigSchema,
  isDefault: z.boolean(),
  enabled: z.boolean(),
  createdAt: DrizzleDateTimeSchema,
  updatedAt: DrizzleDateTimeSchema,
});

export type QaReviewProfile = z.infer<typeof QaReviewProfileSchema>;

export const QaReviewRunSchema = z.object({
  id: z.int(),
  projectId: z.uuidv4(),
  elementId: z.int(),
  translationId: z.int().nullable(),
  qaResultId: z.int().nullable(),
  profileId: z.int().nullable(),
  branchId: z.int().nullable(),
  pullRequestId: z.int().nullable(),
  layer: z.enum(["DETERMINISTIC", "SEMANTIC"]),
  status: z.enum(["COMPLETED", "PARTIAL", "FAILED", "SKIPPED"]),
  checkerServiceId: z.int().nullable(),
  modelServiceId: z.int().nullable(),
  riskScore: z.int(),
  summary: z.string().nullable(),
  errorMessage: z.string().nullable(),
  meta: QaReviewRunMetaSchema.nullable(),
  createdAt: DrizzleDateTimeSchema,
  updatedAt: DrizzleDateTimeSchema,
});

export type QaReviewRun = z.infer<typeof QaReviewRunSchema>;

export const QaReviewFindingSchema = z.object({
  id: z.int(),
  runId: z.int(),
  projectId: z.uuidv4(),
  elementId: z.int(),
  translationId: z.int().nullable(),
  qaResultItemId: z.int().nullable(),
  checkerServiceId: z.int().nullable(),
  layer: z.enum(["DETERMINISTIC", "SEMANTIC"]),
  ruleId: z.string(),
  ruleFamily: z.string(),
  severity: z.string(),
  action: z.enum(["BLOCK_APPROVAL", "NEEDS_REVIEW", "INFORMATIONAL", "PASS", "SUPPRESSED"]),
  disposition: z.enum(["OPEN", "CONFIRMED", "FALSE_POSITIVE", "ACCEPTED", "SUPPRESSED", "SUPERSEDED"]),
  confidenceBasisPoints: z.int(),
  riskScore: z.int(),
  message: z.string(),
  explanation: z.string().nullable(),
  sourceSpan: QaReviewSpanSchema.nullable(),
  targetSpan: QaReviewSpanSchema.nullable(),
  suggestedText: z.string().nullable(),
  reviewedBy: z.uuidv4().nullable(),
  reviewedAt: DrizzleDateTimeSchema.nullable(),
  meta: safeZDotJson.nullable(),
  createdAt: DrizzleDateTimeSchema,
  updatedAt: DrizzleDateTimeSchema,
});

export type QaReviewFinding = z.infer<typeof QaReviewFindingSchema>;

export const QaReviewQueueItemSchema = z.object({
  id: z.int(),
  projectId: z.uuidv4(),
  languageId: z.string(),
  elementId: z.int(),
  translationId: z.int().nullable(),
  branchId: z.int().nullable(),
  pullRequestId: z.int().nullable(),
  scopeKey: z.string(),
  status: z.enum(["OPEN", "CLAIMED", "BLOCKED", "REQUEST_CHANGES", "APPROVABLE", "RESOLVED", "SUPERSEDED"]),
  riskBucket: z.enum(["BLOCKING", "HIGH", "MEDIUM", "LOW", "INFO"]),
  riskScore: z.int(),
  hardFindingCount: z.int(),
  softFindingCount: z.int(),
  informationalFindingCount: z.int(),
  unresolvedAnnotationCount: z.int(),
  annotationCount: z.int(),
  claimedBy: z.uuidv4().nullable(),
  claimedAt: DrizzleDateTimeSchema.nullable(),
  lastFindingAt: DrizzleDateTimeSchema.nullable(),
  lastActivityAt: DrizzleDateTimeSchema,
  resolvedAt: DrizzleDateTimeSchema.nullable(),
  supersededByTranslationId: z.int().nullable(),
  optimisticVersion: z.int(),
  createdAt: DrizzleDateTimeSchema,
  updatedAt: DrizzleDateTimeSchema,
});

export type QaReviewQueueItem = z.infer<typeof QaReviewQueueItemSchema>;

export const QaReviewAnnotationSchema = z.object({
  id: z.int(),
  queueItemId: z.int(),
  projectId: z.uuidv4(),
  elementId: z.int(),
  translationId: z.int().nullable(),
  findingId: z.int().nullable(),
  authorId: z.uuidv4().nullable(),
  authorAgentId: z.int().nullable(),
  branchId: z.int().nullable(),
  pullRequestId: z.int().nullable(),
  intent: z.enum(["ACTION_REQUIRED", "SUGGESTION", "QUESTION", "NOTE", "PRAISE", "WONT_FIX"]),
  status: z.enum(["OPEN", "ACCEPTED", "REJECTED", "RESOLVED", "SUPERSEDED", "HIDDEN"]),
  body: z.string(),
  targetRange: QaReviewTextRangeSchema.nullable(),
  quote: z.string().nullable(),
  isPromotable: z.boolean(),
  promotedContextEvidenceId: z.int().nullable(),
  parentAnnotationId: z.int().nullable(),
  rootAnnotationId: z.int().nullable(),
  metadata: safeZDotJson.nullable(),
  createdAt: DrizzleDateTimeSchema,
  updatedAt: DrizzleDateTimeSchema,
});

export type QaReviewAnnotation = z.infer<typeof QaReviewAnnotationSchema>;

export const QaReviewSuggestionSchema = z.object({
  id: z.int(),
  annotationId: z.int(),
  projectId: z.uuidv4(),
  elementId: z.int(),
  translationId: z.int().nullable(),
  proposedText: z.string(),
  targetRange: QaReviewTextRangeSchema.nullable(),
  status: z.enum(["OPEN", "APPLIED", "REJECTED", "SUPERSEDED"]),
  appliedTranslationId: z.int().nullable(),
  appliedChangesetEntryId: z.int().nullable(),
  appliedBy: z.uuidv4().nullable(),
  appliedAt: DrizzleDateTimeSchema.nullable(),
  rejectionReason: z.string().nullable(),
  metadata: safeZDotJson.nullable(),
  createdAt: DrizzleDateTimeSchema,
  updatedAt: DrizzleDateTimeSchema,
});

export type QaReviewSuggestion = z.infer<typeof QaReviewSuggestionSchema>;

export const QaReviewDecisionSchema = z.object({
  id: z.int(),
  queueItemId: z.int(),
  projectId: z.uuidv4(),
  elementId: z.int(),
  translationId: z.int().nullable(),
  findingId: z.int().nullable(),
  annotationId: z.int().nullable(),
  branchId: z.int().nullable(),
  pullRequestId: z.int().nullable(),
  decision: z.enum(["APPROVE", "REQUEST_CHANGES", "REJECT_CANDIDATE", "CLOSE_FINDING", "PRAISE", "DEFER"]),
  reviewerId: z.uuidv4().nullable(),
  reason: z.string(),
  expectedVersion: z.int(),
  createdAt: DrizzleDateTimeSchema,
  updatedAt: DrizzleDateTimeSchema,
});

export type QaReviewDecision = z.infer<typeof QaReviewDecisionSchema>;
