// Generated by packages/db/src/zod/codegen.ts. Do not edit by hand.
import * as z from "zod/v4";
import { DrizzleDateTimeSchema } from "../misc.ts";
import { safeZDotJson } from "../json.ts";

export const TranslationSchema = z.object({
  id: z.int(),
  translatorId: z.uuidv4().nullable(),
  translatableElementId: z.int(),
  meta: safeZDotJson.nullable(),
  stringId: z.int(),
  createdAt: DrizzleDateTimeSchema,
  updatedAt: DrizzleDateTimeSchema,
});

export type Translation = z.infer<typeof TranslationSchema>;

export const TranslationVoteSchema = z.object({
  id: z.int(),
  value: z.int(),
  voterId: z.uuidv4(),
  translationId: z.int(),
  createdAt: DrizzleDateTimeSchema,
  updatedAt: DrizzleDateTimeSchema,
});

export type TranslationVote = z.infer<typeof TranslationVoteSchema>;

export const TranslationSnapshotSchema = z.object({
  id: z.int(),
  projectId: z.uuidv4(),
  creatorId: z.uuidv4().nullable(),
  createdAt: DrizzleDateTimeSchema,
  updatedAt: DrizzleDateTimeSchema,
});

export type TranslationSnapshot = z.infer<typeof TranslationSnapshotSchema>;

export const TranslationSnapshotItemSchema = z.object({
  id: z.int(),
  snapshotId: z.int(),
  translationId: z.int(),
  createdAt: DrizzleDateTimeSchema,
  updatedAt: DrizzleDateTimeSchema,
});

export type TranslationSnapshotItem = z.infer<typeof TranslationSnapshotItemSchema>;
