// Generated by packages/db/src/zod/codegen.ts. Do not edit by hand.
import * as z from "zod/v4";

import { nonNullSafeZDotJson, safeZDotJson } from "../json.ts";
import { DrizzleDateTimeSchema } from "../misc.ts";

export const UserSchema = z.object({
  id: z.uuidv4(),
  name: z.string(),
  email: z.email(),
  emailVerified: z.boolean(),
  avatarFileId: z.int().nullable(),
  createdAt: DrizzleDateTimeSchema,
  updatedAt: DrizzleDateTimeSchema,
});

export type User = z.infer<typeof UserSchema>;

export const AccountSchema = z.object({
  id: z.int(),
  providerIssuer: z.string(),
  providedAccountId: z.string(),
  meta: safeZDotJson.nullable(),
  userId: z.uuidv4(),
  authProviderId: z.int(),
  createdAt: DrizzleDateTimeSchema,
  updatedAt: DrizzleDateTimeSchema,
});

export type Account = z.infer<typeof AccountSchema>;

export const MFAProviderSchema = z.object({
  id: z.int(),
  failureCount: z.int(),
  lastUsedAt: DrizzleDateTimeSchema.nullable(),
  payload: nonNullSafeZDotJson,
  userId: z.uuidv4(),
  mfaServiceId: z.int(),
  createdAt: DrizzleDateTimeSchema,
  updatedAt: DrizzleDateTimeSchema,
});

export type MFAProvider = z.infer<typeof MFAProviderSchema>;
