// Generated by packages/db/src/zod/codegen.ts. Do not edit by hand.
import * as z from "zod/v4";

import { safeZDotJson } from "../json.ts";
import { DrizzleDateTimeSchema } from "../misc.ts";

export const ChunkSetSchema = z.object({
  id: z.int(),
  meta: safeZDotJson.nullable(),
  createdAt: DrizzleDateTimeSchema,
  updatedAt: DrizzleDateTimeSchema,
});

export type ChunkSet = z.infer<typeof ChunkSetSchema>;

export const ChunkSchema = z.object({
  id: z.int(),
  meta: safeZDotJson.nullable(),
  chunkSetId: z.int(),
  vectorizerId: z.int(),
  vectorStorageId: z.int(),
  createdAt: DrizzleDateTimeSchema,
  updatedAt: DrizzleDateTimeSchema,
});

export type Chunk = z.infer<typeof ChunkSchema>;

export const VectorSchema = z.object({
  id: z.int(),
  vector: z.array(z.number()),
  chunkId: z.int(),
});

export type Vector = z.infer<typeof VectorSchema>;
