ALTER TABLE "PluginService" ALTER COLUMN "service_type" SET DATA TYPE text;
UPDATE "PluginService" 
SET "service_type" = 'FILE_IMPORTER' 
WHERE "service_type" = 'TRANSLATABLE_FILE_HANDLER';
DROP TYPE "PluginServiceType";
CREATE TYPE "PluginServiceType" AS ENUM('AUTH_PROVIDER', 'MFA_PROVIDER', 'STORAGE_PROVIDER', 'TERM_EXTRACTOR', 'TERM_RECOGNIZER', 'TERM_ALIGNER', 'FILE_IMPORTER', 'FILE_EXPORTER', 'TRANSLATION_ADVISOR', 'TEXT_VECTORIZER', 'VECTOR_STORAGE', 'QA_CHECKER');
ALTER TABLE "PluginService" ALTER COLUMN "service_type" SET DATA TYPE "PluginServiceType" USING "service_type"::"PluginServiceType";