import type { PackageInfo, AutodocConfig } from "../types.js";

export const createOverviewRenderer = (
  _config: AutodocConfig,
): { render: (packages: PackageInfo[]) => string } => {
  const render = (packages: PackageInfo[]): string => {
    const lines: string[] = [];

    lines.push("# CAT Project Module Overview");
    lines.push("");
    lines.push(
      "> Auto-generated by autodoc. Descriptions use @en (English) content when bilingual TSDoc is present.",
    );
    lines.push("");

    // Apps section (static)
    lines.push("## Apps");
    lines.push("");
    lines.push("| Package | Path | Description |");
    lines.push("|---------|------|-------------|");
    lines.push("| @cat/app | apps/app | Main app (Vue 3 SSR + Vike) |");
    lines.push("| @cat/app-api | apps/app-api | API layer (Hono + oRPC) |");
    lines.push("| @cat/docs | apps/docs | Documentation site (VitePress) |");
    lines.push("");

    // Core Packages section (dynamic)
    lines.push("## Core Packages");
    lines.push("");
    lines.push("| Package | Path | Functions | Types | Description |");
    lines.push("|---------|------|-----------|-------|-------------|");

    for (const pkg of packages) {
      const funcCount = pkg.modules.reduce(
        (sum, m) => sum + m.functions.length,
        0,
      );
      const typeCount = pkg.modules.reduce((sum, m) => sum + m.types.length, 0);
      const shortName = pkg.name.replace("@cat/", "");
      const desc = pkg.description ?? "-";
      lines.push(
        `| ${pkg.name} | packages/${shortName} | ${funcCount} | ${typeCount} | ${desc} |`,
      );
    }
    lines.push("");

    // Dependency graph
    lines.push("## Core Package Dependencies");
    lines.push("");
    lines.push("```");
    lines.push("operations → domain → db → shared");
    lines.push("permissions → db → shared");
    lines.push("agent → operations → domain");
    lines.push("```");
    lines.push("");

    // Links to package docs
    lines.push("## Package Documentation");
    lines.push("");
    for (const pkg of packages) {
      const shortName = pkg.name.replace("@cat/", "");
      lines.push(`- [${pkg.name}](./packages/${shortName}.md)`);
    }
    lines.push("");

    lines.push(`*Last updated: ${new Date().toISOString().split("T")[0]}*`);

    return lines.join("\n");
  };

  return { render };
};
