ALTER TABLE "TranslatableElementComment" DROP CONSTRAINT "TranslatableElementComment_parent_comment_id_TranslatableElemen";--> statement-breakpoint
ALTER TABLE "TranslatableElementComment" DROP CONSTRAINT "TranslatableElementComment_root_comment_id_TranslatableElementC";--> statement-breakpoint
ALTER TABLE "TranslatableElementComment" DROP CONSTRAINT "TranslatableElementComment_translatable_element_id_Translatable";--> statement-breakpoint
ALTER TABLE "TranslatableElementContext" DROP CONSTRAINT "TranslatableElementContext_storage_provider_id_PluginService_id";--> statement-breakpoint
ALTER TABLE "TranslatableElementContext" DROP CONSTRAINT "TranslatableElementContext_translatable_element_id_Translatable";--> statement-breakpoint
DROP TABLE "drizzle"."__drizzle_migrations";--> statement-breakpoint
ALTER INDEX "PluginService_service_type_service_id_plugin_installation_id_in" RENAME TO "PluginService_service_type_service_id_plugin_installation_id_index";--> statement-breakpoint
ALTER INDEX "TranslatableElementCommentReaction_translatable_element_comment" RENAME TO "TranslatableElementCommentReaction_translatable_element_comment_id_index";--> statement-breakpoint
ALTER INDEX "Translation_translator_id_translatable_element_id_string_id_ind" RENAME TO "Translation_translator_id_translatable_element_id_string_id_index";--> statement-breakpoint
ALTER TABLE "Account" RENAME CONSTRAINT "Account_provider_provided_account_id_pk" TO "Account_pkey";--> statement-breakpoint
ALTER TABLE "DocumentClosure" RENAME CONSTRAINT "DocumentClosure_ancestor_descendant_pk" TO "DocumentClosure_pkey";--> statement-breakpoint
ALTER TABLE "DocumentToTask" RENAME CONSTRAINT "DocumentToTask_document_id_task_id_pk" TO "DocumentToTask_pkey";--> statement-breakpoint
ALTER TABLE "GlossaryToProject" RENAME CONSTRAINT "GlossaryToProject_glossary_id_project_id_pk" TO "GlossaryToProject_pkey";--> statement-breakpoint
ALTER TABLE "MemoryToProject" RENAME CONSTRAINT "MemoryToProject_memory_id_project_id_pk" TO "MemoryToProject_pkey";--> statement-breakpoint
ALTER TABLE "ProjectTargetLanguage" RENAME CONSTRAINT "ProjectTargetLanguage_language_id_project_id_pk" TO "ProjectTargetLanguage_pkey";--> statement-breakpoint
ALTER TABLE "RolePermission" RENAME CONSTRAINT "RolePermission_role_id_permission_id_pk" TO "RolePermission_pkey";--> statement-breakpoint
ALTER TABLE "UserRole" RENAME CONSTRAINT "UserRole_user_id_role_id_pk" TO "UserRole_pkey";--> statement-breakpoint
ALTER TABLE "Account" RENAME CONSTRAINT "Account_user_id_User_id_fk" TO "Account_user_id_User_id_fkey";--> statement-breakpoint
ALTER TABLE "Blob" RENAME CONSTRAINT "Blob_storage_provider_id_PluginService_id_fk" TO "Blob_storage_provider_id_PluginService_id_fkey";--> statement-breakpoint
ALTER TABLE "Chunk" RENAME CONSTRAINT "Chunk_chunk_set_id_ChunkSet_id_fk" TO "Chunk_chunk_set_id_ChunkSet_id_fkey";--> statement-breakpoint
ALTER TABLE "Chunk" RENAME CONSTRAINT "Chunk_vectorizer_id_PluginService_id_fk" TO "Chunk_vectorizer_id_PluginService_id_fkey";--> statement-breakpoint
ALTER TABLE "Document" RENAME CONSTRAINT "Document_project_id_Project_id_fk" TO "Document_project_id_Project_id_fkey";--> statement-breakpoint
ALTER TABLE "Document" RENAME CONSTRAINT "Document_creator_id_User_id_fk" TO "Document_creator_id_User_id_fkey";--> statement-breakpoint
ALTER TABLE "Document" RENAME CONSTRAINT "Document_file_handler_id_PluginService_id_fk" TO "Document_file_handler_id_PluginService_id_fkey";--> statement-breakpoint
ALTER TABLE "Document" RENAME CONSTRAINT "Document_file_id_File_id_fk" TO "Document_file_id_File_id_fkey";--> statement-breakpoint
ALTER TABLE "DocumentClosure" RENAME CONSTRAINT "DocumentClosure_ancestor_Document_id_fk" TO "DocumentClosure_ancestor_Document_id_fkey";--> statement-breakpoint
ALTER TABLE "DocumentClosure" RENAME CONSTRAINT "DocumentClosure_descendant_Document_id_fk" TO "DocumentClosure_descendant_Document_id_fkey";--> statement-breakpoint
ALTER TABLE "DocumentClosure" RENAME CONSTRAINT "DocumentClosure_project_id_Project_id_fk" TO "DocumentClosure_project_id_Project_id_fkey";--> statement-breakpoint
ALTER TABLE "DocumentToTask" RENAME CONSTRAINT "DocumentToTask_document_id_Document_id_fk" TO "DocumentToTask_document_id_Document_id_fkey";--> statement-breakpoint
ALTER TABLE "DocumentToTask" RENAME CONSTRAINT "DocumentToTask_task_id_Task_id_fk" TO "DocumentToTask_task_id_Task_id_fkey";--> statement-breakpoint
ALTER TABLE "DocumentVersion" RENAME CONSTRAINT "DocumentVersion_document_id_Document_id_fk" TO "DocumentVersion_document_id_Document_id_fkey";--> statement-breakpoint
ALTER TABLE "File" RENAME CONSTRAINT "File_blob_id_Blob_id_fk" TO "File_blob_id_Blob_id_fkey";--> statement-breakpoint
ALTER TABLE "Glossary" RENAME CONSTRAINT "Glossary_creator_id_User_id_fk" TO "Glossary_creator_id_User_id_fkey";--> statement-breakpoint
ALTER TABLE "GlossaryToProject" RENAME CONSTRAINT "GlossaryToProject_glossary_id_Glossary_id_fk" TO "GlossaryToProject_glossary_id_Glossary_id_fkey";--> statement-breakpoint
ALTER TABLE "GlossaryToProject" RENAME CONSTRAINT "GlossaryToProject_project_id_Project_id_fk" TO "GlossaryToProject_project_id_Project_id_fkey";--> statement-breakpoint
ALTER TABLE "Memory" RENAME CONSTRAINT "Memory_creator_id_User_id_fk" TO "Memory_creator_id_User_id_fkey";--> statement-breakpoint
ALTER TABLE "MemoryItem" RENAME CONSTRAINT "MemoryItem_creator_id_User_id_fk" TO "MemoryItem_creator_id_User_id_fkey";--> statement-breakpoint
ALTER TABLE "MemoryItem" RENAME CONSTRAINT "MemoryItem_memory_id_Memory_id_fk" TO "MemoryItem_memory_id_Memory_id_fkey";--> statement-breakpoint
ALTER TABLE "MemoryItem" RENAME CONSTRAINT "MemoryItem_source_element_id_TranslatableElement_id_fk" TO "MemoryItem_source_element_id_TranslatableElement_id_fkey";--> statement-breakpoint
ALTER TABLE "MemoryItem" RENAME CONSTRAINT "MemoryItem_translation_id_Translation_id_fk" TO "MemoryItem_translation_id_Translation_id_fkey";--> statement-breakpoint
ALTER TABLE "MemoryItem" RENAME CONSTRAINT "MemoryItem_source_string_id_TranslatableString_id_fk" TO "MemoryItem_source_string_id_TranslatableString_id_fkey";--> statement-breakpoint
ALTER TABLE "MemoryItem" RENAME CONSTRAINT "MemoryItem_translation_string_id_TranslatableString_id_fk" TO "MemoryItem_translation_string_id_TranslatableString_id_fkey";--> statement-breakpoint
ALTER TABLE "MemoryToProject" RENAME CONSTRAINT "MemoryToProject_memory_id_Memory_id_fk" TO "MemoryToProject_memory_id_Memory_id_fkey";--> statement-breakpoint
ALTER TABLE "MemoryToProject" RENAME CONSTRAINT "MemoryToProject_project_id_Project_id_fk" TO "MemoryToProject_project_id_Project_id_fkey";--> statement-breakpoint
ALTER TABLE "Permission" RENAME CONSTRAINT "Permission_template_id_PermissionTemplate_id_fk" TO "Permission_template_id_PermissionTemplate_id_fkey";--> statement-breakpoint
ALTER TABLE "PluginConfig" RENAME CONSTRAINT "PluginConfig_plugin_id_Plugin_id_fk" TO "PluginConfig_plugin_id_Plugin_id_fkey";--> statement-breakpoint
ALTER TABLE "PluginConfigInstance" RENAME CONSTRAINT "PluginConfigInstance_creator_id_User_id_fk" TO "PluginConfigInstance_creator_id_User_id_fkey";--> statement-breakpoint
ALTER TABLE "PluginConfigInstance" RENAME CONSTRAINT "PluginConfigInstance_config_id_PluginConfig_id_fk" TO "PluginConfigInstance_config_id_PluginConfig_id_fkey";--> statement-breakpoint
ALTER TABLE "PluginConfigInstance" RENAME CONSTRAINT "PluginConfigInstance_plugin_installation_id_PluginInstallation_" TO "PluginConfigInstance_tUFft8obCY8T_fkey";--> statement-breakpoint
ALTER TABLE "PluginInstallation" RENAME CONSTRAINT "PluginInstallation_plugin_id_Plugin_id_fk" TO "PluginInstallation_plugin_id_Plugin_id_fkey";--> statement-breakpoint
ALTER TABLE "PluginService" RENAME CONSTRAINT "PluginService_plugin_installation_id_PluginInstallation_id_fk" TO "PluginService_plugin_installation_id_PluginInstallation_id_fkey";--> statement-breakpoint
ALTER TABLE "Project" RENAME CONSTRAINT "Project_creator_id_User_id_fk" TO "Project_creator_id_User_id_fkey";--> statement-breakpoint
ALTER TABLE "ProjectTargetLanguage" RENAME CONSTRAINT "ProjectTargetLanguage_language_id_Language_id_fk" TO "ProjectTargetLanguage_language_id_Language_id_fkey";--> statement-breakpoint
ALTER TABLE "ProjectTargetLanguage" RENAME CONSTRAINT "ProjectTargetLanguage_project_id_Project_id_fk" TO "ProjectTargetLanguage_project_id_Project_id_fkey";--> statement-breakpoint
ALTER TABLE "Role" RENAME CONSTRAINT "Role_creator_id_User_id_fk" TO "Role_creator_id_User_id_fkey";--> statement-breakpoint
ALTER TABLE "RolePermission" RENAME CONSTRAINT "RolePermission_role_id_Role_id_fk" TO "RolePermission_role_id_Role_id_fkey";--> statement-breakpoint
ALTER TABLE "RolePermission" RENAME CONSTRAINT "RolePermission_permission_id_Permission_id_fk" TO "RolePermission_permission_id_Permission_id_fkey";--> statement-breakpoint
ALTER TABLE "Term" RENAME CONSTRAINT "Term_creator_id_User_id_fk" TO "Term_creator_id_User_id_fkey";--> statement-breakpoint
ALTER TABLE "Term" RENAME CONSTRAINT "Term_glossary_id_Glossary_id_fk" TO "Term_glossary_id_Glossary_id_fkey";--> statement-breakpoint
ALTER TABLE "Term" RENAME CONSTRAINT "Term_string_id_TranslatableString_id_fk" TO "Term_string_id_TranslatableString_id_fkey";--> statement-breakpoint
ALTER TABLE "TermRelation" RENAME CONSTRAINT "TermRelation_term_id_Term_id_fk" TO "TermRelation_term_id_Term_id_fkey";--> statement-breakpoint
ALTER TABLE "TermRelation" RENAME CONSTRAINT "TermRelation_translation_id_Term_id_fk" TO "TermRelation_translation_id_Term_id_fkey";--> statement-breakpoint
ALTER TABLE "TranslatableElement" RENAME CONSTRAINT "TranslatableElement_document_id_Document_id_fk" TO "TranslatableElement_document_id_Document_id_fkey";--> statement-breakpoint
ALTER TABLE "TranslatableElement" RENAME CONSTRAINT "TranslatableElement_document_version_id_DocumentVersion_id_fk" TO "TranslatableElement_document_version_id_DocumentVersion_id_fkey";--> statement-breakpoint
ALTER TABLE "TranslatableElement" RENAME CONSTRAINT "TranslatableElement_creator_id_User_id_fk" TO "TranslatableElement_creator_id_User_id_fkey";--> statement-breakpoint
ALTER TABLE "TranslatableElement" RENAME CONSTRAINT "TranslatableElement_translatable_string_id_TranslatableString_i" TO "TranslatableElement_mKNyfTsRaxW6_fkey";--> statement-breakpoint
ALTER TABLE "TranslatableElementComment" RENAME CONSTRAINT "TranslatableElementComment_user_id_User_id_fk" TO "TranslatableElementComment_user_id_User_id_fkey";--> statement-breakpoint
ALTER TABLE "TranslatableElementComment" RENAME CONSTRAINT "TranslatableElementComment_language_id_Language_id_fk" TO "TranslatableElementComment_language_id_Language_id_fkey";--> statement-breakpoint
ALTER TABLE "TranslatableElementCommentReaction" RENAME CONSTRAINT "TranslatableElementCommentReaction_translatable_element_comment" TO "TranslatableElementCommentReaction_KPjwkNbfQ9zz_fkey";--> statement-breakpoint
ALTER TABLE "TranslatableElementCommentReaction" RENAME CONSTRAINT "TranslatableElementCommentReaction_user_id_User_id_fk" TO "TranslatableElementCommentReaction_user_id_User_id_fkey";--> statement-breakpoint
ALTER TABLE "TranslatableElementContext" RENAME CONSTRAINT "TranslatableElementContext_file_id_File_id_fk" TO "TranslatableElementContext_file_id_File_id_fkey";--> statement-breakpoint
ALTER TABLE "TranslatableString" RENAME CONSTRAINT "TranslatableString_language_id_Language_id_fk" TO "TranslatableString_language_id_Language_id_fkey";--> statement-breakpoint
ALTER TABLE "TranslatableString" RENAME CONSTRAINT "TranslatableString_chunk_set_id_ChunkSet_id_fk" TO "TranslatableString_chunk_set_id_ChunkSet_id_fkey";--> statement-breakpoint
ALTER TABLE "Translation" RENAME CONSTRAINT "Translation_translator_id_User_id_fk" TO "Translation_translator_id_User_id_fkey";--> statement-breakpoint
ALTER TABLE "Translation" RENAME CONSTRAINT "Translation_translatable_element_id_TranslatableElement_id_fk" TO "Translation_translatable_element_id_TranslatableElement_id_fkey";--> statement-breakpoint
ALTER TABLE "Translation" RENAME CONSTRAINT "Translation_string_id_TranslatableString_id_fk" TO "Translation_string_id_TranslatableString_id_fkey";--> statement-breakpoint
ALTER TABLE "TranslationApprovement" RENAME CONSTRAINT "TranslationApprovement_translation_id_Translation_id_fk" TO "TranslationApprovement_translation_id_Translation_id_fkey";--> statement-breakpoint
ALTER TABLE "TranslationApprovement" RENAME CONSTRAINT "TranslationApprovement_creator_id_User_id_fk" TO "TranslationApprovement_creator_id_User_id_fkey";--> statement-breakpoint
ALTER TABLE "TranslationVote" RENAME CONSTRAINT "TranslationVote_voter_id_User_id_fk" TO "TranslationVote_voter_id_User_id_fkey";--> statement-breakpoint
ALTER TABLE "TranslationVote" RENAME CONSTRAINT "TranslationVote_translation_id_Translation_id_fk" TO "TranslationVote_translation_id_Translation_id_fkey";--> statement-breakpoint
ALTER TABLE "User" RENAME CONSTRAINT "User_avatar_file_id_File_id_fk" TO "User_avatar_file_id_File_id_fkey";--> statement-breakpoint
ALTER TABLE "UserRole" RENAME CONSTRAINT "UserRole_user_id_User_id_fk" TO "UserRole_user_id_User_id_fkey";--> statement-breakpoint
ALTER TABLE "UserRole" RENAME CONSTRAINT "UserRole_role_id_Role_id_fk" TO "UserRole_role_id_Role_id_fkey";--> statement-breakpoint
ALTER TABLE "Vector" RENAME CONSTRAINT "Vector_chunk_id_Chunk_id_fk" TO "Vector_chunk_id_Chunk_id_fkey";--> statement-breakpoint
ALTER TABLE "User" ALTER COLUMN "id" SET DEFAULT 'uuidv7()';--> statement-breakpoint
ALTER TABLE "Memory" ALTER COLUMN "id" SET DEFAULT 'uuidv7()';--> statement-breakpoint
ALTER TABLE "Document" ALTER COLUMN "id" SET DEFAULT 'uuidv7()';--> statement-breakpoint
ALTER TABLE "Task" ALTER COLUMN "id" SET DEFAULT 'uuidv7()';--> statement-breakpoint
ALTER TABLE "Glossary" ALTER COLUMN "id" SET DEFAULT 'uuidv7()';--> statement-breakpoint
ALTER TABLE "Project" ALTER COLUMN "id" SET DEFAULT 'uuidv7()';--> statement-breakpoint
ALTER TABLE "RolePermission" ALTER COLUMN "role_id" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "RolePermission" ALTER COLUMN "permission_id" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "Blob" RENAME CONSTRAINT "Blob_storageProviderId_key_unique" TO "Blob_storage_provider_id_key_unique";--> statement-breakpoint
ALTER TABLE "PermissionTemplate" RENAME CONSTRAINT "PermissionTemplate_content_resourceType_unique" TO "PermissionTemplate_content_resource_type_unique";--> statement-breakpoint
ALTER TABLE "Role" RENAME CONSTRAINT "Role_name_scopeType_scopeId_unique" TO "Role_name_scope_type_scope_id_unique";--> statement-breakpoint
ALTER TABLE "TranslatableElementCommentReaction" RENAME CONSTRAINT "TranslatableElementCommentReaction_translatableElementCommentId" TO "TranslatableElementCommentReaction_translatable_element_comment_id_user_id_unique";--> statement-breakpoint
ALTER TABLE "TranslatableString" RENAME CONSTRAINT "TranslatableString_languageId_value_unique" TO "TranslatableString_language_id_value_unique";--> statement-breakpoint
ALTER TABLE "TranslatableElementComment" ADD CONSTRAINT "TranslatableElementComment_XcPkwxltYBq7_fkey" FOREIGN KEY ("translatable_element_id") REFERENCES "TranslatableElement"("id") ON DELETE CASCADE ON UPDATE CASCADE;--> statement-breakpoint
ALTER TABLE "TranslatableElementComment" ADD CONSTRAINT "TranslatableElementComment_rVcH2vk2wZwM_fkey" FOREIGN KEY ("parent_comment_id") REFERENCES "TranslatableElementComment"("id") ON DELETE SET NULL ON UPDATE CASCADE;--> statement-breakpoint
ALTER TABLE "TranslatableElementComment" ADD CONSTRAINT "TranslatableElementComment_csrAMZXJDU4O_fkey" FOREIGN KEY ("root_comment_id") REFERENCES "TranslatableElementComment"("id") ON DELETE SET NULL ON UPDATE CASCADE;--> statement-breakpoint
ALTER TABLE "TranslatableElementContext" ADD CONSTRAINT "TranslatableElementContext_ocSqg69uUW3x_fkey" FOREIGN KEY ("storage_provider_id") REFERENCES "PluginService"("id") ON DELETE CASCADE ON UPDATE CASCADE;--> statement-breakpoint
ALTER TABLE "TranslatableElementContext" ADD CONSTRAINT "TranslatableElementContext_1bh40XM18KpL_fkey" FOREIGN KEY ("translatable_element_id") REFERENCES "TranslatableElement"("id") ON DELETE CASCADE ON UPDATE CASCADE;--> statement-breakpoint
ALTER TABLE "Document" DROP CONSTRAINT "Document_creator_id_User_id_fkey", ADD CONSTRAINT "Document_creator_id_User_id_fkey" FOREIGN KEY ("creator_id") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;--> statement-breakpoint
ALTER TABLE "Document" DROP CONSTRAINT "Document_file_handler_id_PluginService_id_fkey", ADD CONSTRAINT "Document_file_handler_id_PluginService_id_fkey" FOREIGN KEY ("file_handler_id") REFERENCES "PluginService"("id") ON DELETE SET NULL ON UPDATE CASCADE;--> statement-breakpoint
ALTER TABLE "Document" DROP CONSTRAINT "Document_file_id_File_id_fkey", ADD CONSTRAINT "Document_file_id_File_id_fkey" FOREIGN KEY ("file_id") REFERENCES "File"("id") ON DELETE SET NULL ON UPDATE CASCADE;--> statement-breakpoint
ALTER TABLE "Document" DROP CONSTRAINT "Document_project_id_Project_id_fkey", ADD CONSTRAINT "Document_project_id_Project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "Project"("id") ON DELETE CASCADE ON UPDATE CASCADE;--> statement-breakpoint
ALTER TABLE "DocumentToTask" DROP CONSTRAINT "DocumentToTask_document_id_Document_id_fkey", ADD CONSTRAINT "DocumentToTask_document_id_Document_id_fkey" FOREIGN KEY ("document_id") REFERENCES "Document"("id") ON DELETE CASCADE ON UPDATE CASCADE;--> statement-breakpoint
ALTER TABLE "DocumentToTask" DROP CONSTRAINT "DocumentToTask_task_id_Task_id_fkey", ADD CONSTRAINT "DocumentToTask_task_id_Task_id_fkey" FOREIGN KEY ("task_id") REFERENCES "Task"("id") ON DELETE CASCADE ON UPDATE CASCADE;--> statement-breakpoint
ALTER TABLE "DocumentVersion" DROP CONSTRAINT "DocumentVersion_document_id_Document_id_fkey", ADD CONSTRAINT "DocumentVersion_document_id_Document_id_fkey" FOREIGN KEY ("document_id") REFERENCES "Document"("id") ON DELETE CASCADE ON UPDATE CASCADE;--> statement-breakpoint
ALTER TABLE "TranslatableElement" DROP CONSTRAINT "TranslatableElement_creator_id_User_id_fkey", ADD CONSTRAINT "TranslatableElement_creator_id_User_id_fkey" FOREIGN KEY ("creator_id") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;--> statement-breakpoint
ALTER TABLE "TranslatableElement" DROP CONSTRAINT "TranslatableElement_document_id_Document_id_fkey", ADD CONSTRAINT "TranslatableElement_document_id_Document_id_fkey" FOREIGN KEY ("document_id") REFERENCES "Document"("id") ON DELETE CASCADE ON UPDATE CASCADE;--> statement-breakpoint
ALTER TABLE "TranslatableElement" DROP CONSTRAINT "TranslatableElement_document_version_id_DocumentVersion_id_fkey", ADD CONSTRAINT "TranslatableElement_document_version_id_DocumentVersion_id_fkey" FOREIGN KEY ("document_version_id") REFERENCES "DocumentVersion"("id") ON DELETE SET NULL ON UPDATE CASCADE;--> statement-breakpoint
ALTER TABLE "TranslatableElement" DROP CONSTRAINT "TranslatableElement_mKNyfTsRaxW6_fkey", ADD CONSTRAINT "TranslatableElement_mKNyfTsRaxW6_fkey" FOREIGN KEY ("translatable_string_id") REFERENCES "TranslatableString"("id") ON DELETE RESTRICT ON UPDATE CASCADE;--> statement-breakpoint
ALTER TABLE "File" DROP CONSTRAINT "File_blob_id_Blob_id_fkey", ADD CONSTRAINT "File_blob_id_Blob_id_fkey" FOREIGN KEY ("blob_id") REFERENCES "Blob"("id") ON DELETE RESTRICT ON UPDATE CASCADE;--> statement-breakpoint
ALTER TABLE "Glossary" DROP CONSTRAINT "Glossary_creator_id_User_id_fkey", ADD CONSTRAINT "Glossary_creator_id_User_id_fkey" FOREIGN KEY ("creator_id") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;--> statement-breakpoint
ALTER TABLE "GlossaryToProject" DROP CONSTRAINT "GlossaryToProject_glossary_id_Glossary_id_fkey", ADD CONSTRAINT "GlossaryToProject_glossary_id_Glossary_id_fkey" FOREIGN KEY ("glossary_id") REFERENCES "Glossary"("id") ON DELETE CASCADE ON UPDATE CASCADE;--> statement-breakpoint
ALTER TABLE "GlossaryToProject" DROP CONSTRAINT "GlossaryToProject_project_id_Project_id_fkey", ADD CONSTRAINT "GlossaryToProject_project_id_Project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "Project"("id") ON DELETE CASCADE ON UPDATE CASCADE;--> statement-breakpoint
ALTER TABLE "Term" DROP CONSTRAINT "Term_creator_id_User_id_fkey", ADD CONSTRAINT "Term_creator_id_User_id_fkey" FOREIGN KEY ("creator_id") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;--> statement-breakpoint
ALTER TABLE "Term" DROP CONSTRAINT "Term_glossary_id_Glossary_id_fkey", ADD CONSTRAINT "Term_glossary_id_Glossary_id_fkey" FOREIGN KEY ("glossary_id") REFERENCES "Glossary"("id") ON DELETE CASCADE ON UPDATE CASCADE;--> statement-breakpoint
ALTER TABLE "Term" DROP CONSTRAINT "Term_string_id_TranslatableString_id_fkey", ADD CONSTRAINT "Term_string_id_TranslatableString_id_fkey" FOREIGN KEY ("string_id") REFERENCES "TranslatableString"("id") ON DELETE RESTRICT ON UPDATE CASCADE;--> statement-breakpoint
ALTER TABLE "TermRelation" DROP CONSTRAINT "TermRelation_term_id_Term_id_fkey", ADD CONSTRAINT "TermRelation_term_id_Term_id_fkey" FOREIGN KEY ("term_id") REFERENCES "Term"("id") ON DELETE RESTRICT ON UPDATE CASCADE;--> statement-breakpoint
ALTER TABLE "TermRelation" DROP CONSTRAINT "TermRelation_translation_id_Term_id_fkey", ADD CONSTRAINT "TermRelation_translation_id_Term_id_fkey" FOREIGN KEY ("translation_id") REFERENCES "Term"("id") ON DELETE RESTRICT ON UPDATE CASCADE;--> statement-breakpoint
ALTER TABLE "Memory" DROP CONSTRAINT "Memory_creator_id_User_id_fkey", ADD CONSTRAINT "Memory_creator_id_User_id_fkey" FOREIGN KEY ("creator_id") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;--> statement-breakpoint
ALTER TABLE "MemoryItem" DROP CONSTRAINT "MemoryItem_creator_id_User_id_fkey", ADD CONSTRAINT "MemoryItem_creator_id_User_id_fkey" FOREIGN KEY ("creator_id") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;--> statement-breakpoint
ALTER TABLE "MemoryItem" DROP CONSTRAINT "MemoryItem_memory_id_Memory_id_fkey", ADD CONSTRAINT "MemoryItem_memory_id_Memory_id_fkey" FOREIGN KEY ("memory_id") REFERENCES "Memory"("id") ON DELETE CASCADE ON UPDATE CASCADE;--> statement-breakpoint
ALTER TABLE "MemoryItem" DROP CONSTRAINT "MemoryItem_source_element_id_TranslatableElement_id_fkey", ADD CONSTRAINT "MemoryItem_source_element_id_TranslatableElement_id_fkey" FOREIGN KEY ("source_element_id") REFERENCES "TranslatableElement"("id") ON DELETE SET NULL ON UPDATE CASCADE;--> statement-breakpoint
ALTER TABLE "MemoryItem" DROP CONSTRAINT "MemoryItem_source_string_id_TranslatableString_id_fkey", ADD CONSTRAINT "MemoryItem_source_string_id_TranslatableString_id_fkey" FOREIGN KEY ("source_string_id") REFERENCES "TranslatableString"("id") ON DELETE RESTRICT ON UPDATE CASCADE;--> statement-breakpoint
ALTER TABLE "MemoryItem" DROP CONSTRAINT "MemoryItem_translation_id_Translation_id_fkey", ADD CONSTRAINT "MemoryItem_translation_id_Translation_id_fkey" FOREIGN KEY ("translation_id") REFERENCES "Translation"("id") ON DELETE SET NULL ON UPDATE CASCADE;--> statement-breakpoint
ALTER TABLE "MemoryItem" DROP CONSTRAINT "MemoryItem_translation_string_id_TranslatableString_id_fkey", ADD CONSTRAINT "MemoryItem_translation_string_id_TranslatableString_id_fkey" FOREIGN KEY ("translation_string_id") REFERENCES "TranslatableString"("id") ON DELETE RESTRICT ON UPDATE CASCADE;--> statement-breakpoint
ALTER TABLE "MemoryToProject" DROP CONSTRAINT "MemoryToProject_memory_id_Memory_id_fkey", ADD CONSTRAINT "MemoryToProject_memory_id_Memory_id_fkey" FOREIGN KEY ("memory_id") REFERENCES "Memory"("id") ON DELETE CASCADE ON UPDATE CASCADE;--> statement-breakpoint
ALTER TABLE "MemoryToProject" DROP CONSTRAINT "MemoryToProject_project_id_Project_id_fkey", ADD CONSTRAINT "MemoryToProject_project_id_Project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "Project"("id") ON DELETE CASCADE ON UPDATE CASCADE;--> statement-breakpoint
ALTER TABLE "PluginConfig" DROP CONSTRAINT "PluginConfig_plugin_id_Plugin_id_fkey", ADD CONSTRAINT "PluginConfig_plugin_id_Plugin_id_fkey" FOREIGN KEY ("plugin_id") REFERENCES "Plugin"("id") ON DELETE CASCADE ON UPDATE CASCADE;--> statement-breakpoint
ALTER TABLE "PluginConfigInstance" DROP CONSTRAINT "PluginConfigInstance_config_id_PluginConfig_id_fkey", ADD CONSTRAINT "PluginConfigInstance_config_id_PluginConfig_id_fkey" FOREIGN KEY ("config_id") REFERENCES "PluginConfig"("id") ON DELETE CASCADE ON UPDATE CASCADE;--> statement-breakpoint
ALTER TABLE "PluginConfigInstance" DROP CONSTRAINT "PluginConfigInstance_creator_id_User_id_fkey", ADD CONSTRAINT "PluginConfigInstance_creator_id_User_id_fkey" FOREIGN KEY ("creator_id") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;--> statement-breakpoint
ALTER TABLE "PluginConfigInstance" DROP CONSTRAINT "PluginConfigInstance_tUFft8obCY8T_fkey", ADD CONSTRAINT "PluginConfigInstance_tUFft8obCY8T_fkey" FOREIGN KEY ("plugin_installation_id") REFERENCES "PluginInstallation"("id") ON DELETE CASCADE ON UPDATE CASCADE;--> statement-breakpoint
ALTER TABLE "PluginInstallation" DROP CONSTRAINT "PluginInstallation_plugin_id_Plugin_id_fkey", ADD CONSTRAINT "PluginInstallation_plugin_id_Plugin_id_fkey" FOREIGN KEY ("plugin_id") REFERENCES "Plugin"("id") ON DELETE CASCADE ON UPDATE CASCADE;--> statement-breakpoint
ALTER TABLE "PluginService" DROP CONSTRAINT "PluginService_plugin_installation_id_PluginInstallation_id_fkey", ADD CONSTRAINT "PluginService_plugin_installation_id_PluginInstallation_id_fkey" FOREIGN KEY ("plugin_installation_id") REFERENCES "PluginInstallation"("id") ON DELETE CASCADE ON UPDATE CASCADE;--> statement-breakpoint
ALTER TABLE "Project" DROP CONSTRAINT "Project_creator_id_User_id_fkey", ADD CONSTRAINT "Project_creator_id_User_id_fkey" FOREIGN KEY ("creator_id") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;--> statement-breakpoint
ALTER TABLE "ProjectTargetLanguage" DROP CONSTRAINT "ProjectTargetLanguage_language_id_Language_id_fkey", ADD CONSTRAINT "ProjectTargetLanguage_language_id_Language_id_fkey" FOREIGN KEY ("language_id") REFERENCES "Language"("id") ON DELETE CASCADE ON UPDATE CASCADE;--> statement-breakpoint
ALTER TABLE "ProjectTargetLanguage" DROP CONSTRAINT "ProjectTargetLanguage_project_id_Project_id_fkey", ADD CONSTRAINT "ProjectTargetLanguage_project_id_Project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "Project"("id") ON DELETE CASCADE ON UPDATE CASCADE;--> statement-breakpoint
ALTER TABLE "Translation" DROP CONSTRAINT "Translation_string_id_TranslatableString_id_fkey", ADD CONSTRAINT "Translation_string_id_TranslatableString_id_fkey" FOREIGN KEY ("string_id") REFERENCES "TranslatableString"("id") ON DELETE RESTRICT ON UPDATE CASCADE;--> statement-breakpoint
ALTER TABLE "Translation" DROP CONSTRAINT "Translation_translatable_element_id_TranslatableElement_id_fkey", ADD CONSTRAINT "Translation_translatable_element_id_TranslatableElement_id_fkey" FOREIGN KEY ("translatable_element_id") REFERENCES "TranslatableElement"("id") ON DELETE CASCADE ON UPDATE CASCADE;--> statement-breakpoint
ALTER TABLE "Translation" DROP CONSTRAINT "Translation_translator_id_User_id_fkey", ADD CONSTRAINT "Translation_translator_id_User_id_fkey" FOREIGN KEY ("translator_id") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;--> statement-breakpoint
ALTER TABLE "TranslationApprovement" DROP CONSTRAINT "TranslationApprovement_creator_id_User_id_fkey", ADD CONSTRAINT "TranslationApprovement_creator_id_User_id_fkey" FOREIGN KEY ("creator_id") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;--> statement-breakpoint
ALTER TABLE "TranslationApprovement" DROP CONSTRAINT "TranslationApprovement_translation_id_Translation_id_fkey", ADD CONSTRAINT "TranslationApprovement_translation_id_Translation_id_fkey" FOREIGN KEY ("translation_id") REFERENCES "Translation"("id") ON DELETE CASCADE ON UPDATE CASCADE;--> statement-breakpoint
ALTER TABLE "TranslationVote" DROP CONSTRAINT "TranslationVote_translation_id_Translation_id_fkey", ADD CONSTRAINT "TranslationVote_translation_id_Translation_id_fkey" FOREIGN KEY ("translation_id") REFERENCES "Translation"("id") ON DELETE CASCADE ON UPDATE CASCADE;--> statement-breakpoint
ALTER TABLE "TranslationVote" DROP CONSTRAINT "TranslationVote_voter_id_User_id_fkey", ADD CONSTRAINT "TranslationVote_voter_id_User_id_fkey" FOREIGN KEY ("voter_id") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;--> statement-breakpoint
ALTER TABLE "Account" DROP CONSTRAINT "Account_user_id_User_id_fkey", ADD CONSTRAINT "Account_user_id_User_id_fkey" FOREIGN KEY ("user_id") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;--> statement-breakpoint
ALTER TABLE "User" DROP CONSTRAINT "User_avatar_file_id_File_id_fkey", ADD CONSTRAINT "User_avatar_file_id_File_id_fkey" FOREIGN KEY ("avatar_file_id") REFERENCES "File"("id") ON DELETE SET NULL ON UPDATE CASCADE;--> statement-breakpoint
ALTER TABLE "Vector" DROP CONSTRAINT "Vector_chunk_id_Chunk_id_fkey", ADD CONSTRAINT "Vector_chunk_id_Chunk_id_fkey" FOREIGN KEY ("chunk_id") REFERENCES "Chunk"("id") ON DELETE CASCADE ON UPDATE CASCADE;--> statement-breakpoint
ALTER TABLE "TranslatableString" DROP CONSTRAINT "TranslatableString_chunk_set_id_ChunkSet_id_fkey", ADD CONSTRAINT "TranslatableString_chunk_set_id_ChunkSet_id_fkey" FOREIGN KEY ("chunk_set_id") REFERENCES "ChunkSet"("id") ON DELETE RESTRICT ON UPDATE CASCADE;--> statement-breakpoint
ALTER TABLE "TranslatableString" DROP CONSTRAINT "TranslatableString_language_id_Language_id_fkey", ADD CONSTRAINT "TranslatableString_language_id_Language_id_fkey" FOREIGN KEY ("language_id") REFERENCES "Language"("id") ON DELETE RESTRICT ON UPDATE CASCADE;--> statement-breakpoint
ALTER TABLE "Chunk" DROP CONSTRAINT "Chunk_chunk_set_id_ChunkSet_id_fkey", ADD CONSTRAINT "Chunk_chunk_set_id_ChunkSet_id_fkey" FOREIGN KEY ("chunk_set_id") REFERENCES "ChunkSet"("id") ON DELETE CASCADE ON UPDATE CASCADE;--> statement-breakpoint
ALTER TABLE "Chunk" DROP CONSTRAINT "Chunk_vectorizer_id_PluginService_id_fkey", ADD CONSTRAINT "Chunk_vectorizer_id_PluginService_id_fkey" FOREIGN KEY ("vectorizer_id") REFERENCES "PluginService"("id") ON DELETE RESTRICT ON UPDATE CASCADE;--> statement-breakpoint
ALTER TABLE "Blob" DROP CONSTRAINT "Blob_storage_provider_id_PluginService_id_fkey", ADD CONSTRAINT "Blob_storage_provider_id_PluginService_id_fkey" FOREIGN KEY ("storage_provider_id") REFERENCES "PluginService"("id") ON DELETE RESTRICT ON UPDATE CASCADE;--> statement-breakpoint
ALTER TABLE "DocumentClosure" DROP CONSTRAINT "DocumentClosure_ancestor_Document_id_fkey", ADD CONSTRAINT "DocumentClosure_ancestor_Document_id_fkey" FOREIGN KEY ("ancestor") REFERENCES "Document"("id") ON DELETE CASCADE ON UPDATE CASCADE;--> statement-breakpoint
ALTER TABLE "DocumentClosure" DROP CONSTRAINT "DocumentClosure_descendant_Document_id_fkey", ADD CONSTRAINT "DocumentClosure_descendant_Document_id_fkey" FOREIGN KEY ("descendant") REFERENCES "Document"("id") ON DELETE CASCADE ON UPDATE CASCADE;--> statement-breakpoint
ALTER TABLE "DocumentClosure" DROP CONSTRAINT "DocumentClosure_project_id_Project_id_fkey", ADD CONSTRAINT "DocumentClosure_project_id_Project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "Project"("id") ON DELETE CASCADE ON UPDATE CASCADE;--> statement-breakpoint
ALTER TABLE "TranslatableElementContext" DROP CONSTRAINT "TranslatableElementContext_file_id_File_id_fkey", ADD CONSTRAINT "TranslatableElementContext_file_id_File_id_fkey" FOREIGN KEY ("file_id") REFERENCES "File"("id") ON DELETE CASCADE ON UPDATE CASCADE;--> statement-breakpoint
ALTER TABLE "TranslatableElementComment" DROP CONSTRAINT "TranslatableElementComment_language_id_Language_id_fkey", ADD CONSTRAINT "TranslatableElementComment_language_id_Language_id_fkey" FOREIGN KEY ("language_id") REFERENCES "Language"("id") ON DELETE RESTRICT ON UPDATE CASCADE;--> statement-breakpoint
ALTER TABLE "TranslatableElementComment" DROP CONSTRAINT "TranslatableElementComment_user_id_User_id_fkey", ADD CONSTRAINT "TranslatableElementComment_user_id_User_id_fkey" FOREIGN KEY ("user_id") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;--> statement-breakpoint
ALTER TABLE "TranslatableElementCommentReaction" DROP CONSTRAINT "TranslatableElementCommentReaction_KPjwkNbfQ9zz_fkey", ADD CONSTRAINT "TranslatableElementCommentReaction_KPjwkNbfQ9zz_fkey" FOREIGN KEY ("translatable_element_comment_id") REFERENCES "TranslatableElementComment"("id") ON DELETE CASCADE ON UPDATE CASCADE;--> statement-breakpoint
ALTER TABLE "TranslatableElementCommentReaction" DROP CONSTRAINT "TranslatableElementCommentReaction_user_id_User_id_fkey", ADD CONSTRAINT "TranslatableElementCommentReaction_user_id_User_id_fkey" FOREIGN KEY ("user_id") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;--> statement-breakpoint
ALTER TABLE "Permission" DROP CONSTRAINT "Permission_template_id_PermissionTemplate_id_fkey", ADD CONSTRAINT "Permission_template_id_PermissionTemplate_id_fkey" FOREIGN KEY ("template_id") REFERENCES "PermissionTemplate"("id") ON DELETE CASCADE ON UPDATE CASCADE;--> statement-breakpoint
ALTER TABLE "Role" DROP CONSTRAINT "Role_creator_id_User_id_fkey", ADD CONSTRAINT "Role_creator_id_User_id_fkey" FOREIGN KEY ("creator_id") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;--> statement-breakpoint
ALTER TABLE "RolePermission" DROP CONSTRAINT "RolePermission_permission_id_Permission_id_fkey", ADD CONSTRAINT "RolePermission_permission_id_Permission_id_fkey" FOREIGN KEY ("permission_id") REFERENCES "Permission"("id") ON DELETE CASCADE ON UPDATE CASCADE;--> statement-breakpoint
ALTER TABLE "RolePermission" DROP CONSTRAINT "RolePermission_role_id_Role_id_fkey", ADD CONSTRAINT "RolePermission_role_id_Role_id_fkey" FOREIGN KEY ("role_id") REFERENCES "Role"("id") ON DELETE CASCADE ON UPDATE CASCADE;--> statement-breakpoint
ALTER TABLE "UserRole" DROP CONSTRAINT "UserRole_role_id_Role_id_fkey", ADD CONSTRAINT "UserRole_role_id_Role_id_fkey" FOREIGN KEY ("role_id") REFERENCES "Role"("id") ON DELETE CASCADE ON UPDATE CASCADE;--> statement-breakpoint
ALTER TABLE "UserRole" DROP CONSTRAINT "UserRole_user_id_User_id_fkey", ADD CONSTRAINT "UserRole_user_id_User_id_fkey" FOREIGN KEY ("user_id") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;