// Generated by packages/shared/scripts/sync-public-contract.ts. Do not edit by hand.
export {
  type Glossary,
  GlossarySchema,
  type GlossaryToProject,
  GlossaryToProjectSchema,
  type Term,
  type TermConcept,
  TermConceptSchema,
  type TermConceptSubject,
  TermConceptSubjectSchema,
  type TermConceptToSubject,
  TermConceptToSubjectSchema,
  type TermRecallVariant,
  TermRecallVariantSchema,
  TermSchema,
} from "../../../index.ts";
