// Generated by packages/shared/scripts/sync-public-contract.ts. Do not edit by hand.
export {
  type Plugin,
  type PluginComponent,
  PluginComponentSchema,
  type PluginConfig,
  type PluginConfigInstance,
  PluginConfigInstanceSchema,
  PluginConfigSchema,
  type PluginInstallation,
  PluginInstallationSchema,
  type PluginPermission,
  PluginPermissionSchema,
  PluginSchema,
  type PluginService,
  PluginServiceSchema,
  type PluginVersion,
  PluginVersionSchema,
} from "../../../index.ts";
