name: Auto-merge Dependabot PRs

on:
  pull_request:
    types: [opened, reopened, labeled, synchronize, ready_for_review]
  check_suite:
    types: [completed]

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    if: |
      (github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]') &&
      github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Auto-approve PR
        uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check mergeability
        id: check
        run: |
          # 检查 CI 状态
          if [[ "${{ github.event_name }}" == "check_suite" ]]; then
            if [[ "${{ github.event.check_suite.conclusion }}" != "success" ]]; then
              echo "CI checks failed" >&2
              exit 1
            fi
          fi

          # 检查冲突/合并状态
          RESPONSE=$(gh pr view ${{ github.event.pull_request.number }} --json mergeable,mergeStateStatus)
          MERGEABLE=$(jq -r '.mergeable' <<< "$RESPONSE")
          MERGE_STATUS=$(jq -r '.mergeStateStatus' <<< "$RESPONSE")

          if [[ "$MERGEABLE" != "MERGEABLE" || "$MERGE_STATUS" != "CLEAN" ]]; then
            echo "PR not mergeable (status: $MERGE_STATUS)" >&2
            exit 1
          fi

      - name: Enable auto-merge for security
        if: |
          contains(github.event.pull_request.labels.*.name, 'security') ||
          contains(github.event.pull_request.title, 'security') ||
          contains(github.event.pull_request.title, 'CVE')
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: squash

      - name: Enable auto-merge for non-security
        if: ${{ !contains(github.event.pull_request.labels.*.name, 'security') }}
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: squash
