name: Auto-merge Dependabot PRs

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  automerge:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge "$PR_URL" --auto --merge
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
