name: Full Code Quality

on:
  workflow_dispatch:

jobs:
  full-quality:
    name: Run All Typcheck, Lint and Format Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Check Generated Drizzle Schemas
        run: pnpm check:generated-schemas

      - name: Run ALL Tasks
        run: pnpm moon run :lint :typecheck :fmt-check
